- environments/development/common/rds.tf
This PR is a fix for #17's apply failure.
I have:
- Changed the instance type on the RDS module to `db.t2.small`.
- `db.t2.micro` does not support encryption at rest (for some reason).
> HOTT-3343: Fix instance type

- environments/development/common/rds.tf
This PR fixes #18...
I have:
- Changed the instance type to `db.t3.micro`.
- According to [the documentation](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.DBInstanceClass.html#Concepts.DBInstanceClass.Support) `db.t2.micro` doesn't support encryption at rest, and `db.t2` instances don't support Postgres >=13. 😞
> HOTT-3343: Change to db.t3.micro

- environments/development/common/rds.tf
I have:
- Changed the database name to `TradeTariffPostgres${title(var.environment)}`
- The database name cannot contain hyphens (what year is it?)
> BAU: RDS DB names cannot contain hyphens

- environments/common/rds/README.md
- environments/common/rds/rds.tf
- environments/common/rds/variables.tf
- environments/development/common/rds.tf
I have:
- Added the ability to configure deletion protection for RDS.
- Turned off final snapshots on deletion.
- While we're configuring it, we'll probably need to make changes that force deletion, which will just block the pipeline. So in this case, I've set it to `false` for `development`.
- We don't need a final snapshot if we're deleting the database through a TF action here. With deletion protection turned on in `production`, we won't see this behaviour.
> BAU: Allow db deletion through variable

- .circleci/config.yml
I have:
- Added ignores for the `fmt` and `plan` jobs on `main`.
- Remove all the commented out code.
- We're PRing everything here, so we don't need to run fmt/plan again when things get merged into `main`, that's just time we aren't going to get back 😢 
- I've removed all the commented out stuff as it's not being used and it's easy to get back later on. This gives us a cleaner view at the pipe
> BAU: Skip fmt/plan jobs on main

- environments/common/elasticache/.terraform.lock.hcl
- environments/common/elasticache/README.md
- environments/common/elasticache/elasticache.tf
- environments/common/elasticache/outputs.tf
- environments/common/elasticache/variables.tf
- environments/common/elasticache/versions.tf
- environments/development/common/README.md
- environments/development/common/cloudwatch.tf
- environments/development/common/redis.tf
- environments/development/common/variables.tf
This pull request forms part of [HOTT-2782](https://transformuk.atlassian.net/browse/HOTT-2782).
I have:
- Added an ElastiCache replication group resource with replica support. This has defaults baked-in for Redis.
- Redis is a requirement for the applications, so we need that up and running first.
> HOTT-2782: Add ElastiCache (Redis) Module

- environments/development/common/cloudwatch.tf
PR to fix the interaction between the KMS key and the Cloudwatch log group.
I have:
- Added a `depends_on` block on the CW group
- There's a race condition between the two resources, but one of them does actually rely on the other or we get weird output.
- It's better that I just fix this now instead of having to run apply twice down the road.
> BAU: Add depends_on block for cloudwatch key

- environments/development/common/README.md
- environments/development/common/cloudwatch.tf
- environments/development/common/locals.tf
I have:
- Removed `condition` block in key policy
- Specify key arn in `resource` block
- Add key alias
- Remove unused `locals.tf`
- The previous PR left us with a `MalformedPolicyDocument` exception. I realised after this applied that what I did was actually more complicated than just specifying the key arn.
- We should have key aliases on our keys; I haven't updated all of them but I will do this in a second/later PR as if we need to look at keys via the AWS CLI or console they are all just specified by ID and that's not useful to us.
> BAU: Update Cloudwatch KMS key policy

- environments/development/common/cloudwatch.tf
I have:
- Fixed the key policy being self-referential
- The key policy needs to allow Cloudwatch to use it
> BAU: Use cloudwatch log group arn

- environments/common/cloudwatch/README.md
- environments/common/cloudwatch/cloudwatch.tf
- environments/common/cloudwatch/locals.tf
- environments/common/cloudwatch/variables.tf
- environments/common/cloudwatch/versions.tf
- environments/common/ecr/ecr.tf
- environments/development/common/cloudwatch.tf
I have:
1. Changed the `kms_key` input to the ECR resource to use the key ARN.
2. Created the KMS key policy for the CloudWatch log group key using only string interpolation.
3. Removed redundant `var.region` and AWS provider blocks.
1. The resource can take either the `key_id` or ARN, but converts either to an ARN. On subsequent runs, using the `key_id` will produce a diff, and Terraform will destroy and recreate the resource on every run. By using the ARN, the value isn't changing on each apply, so there's no diff.
2. There was, despite a `depends_on` block, a reference to the CloudWatch log group resource in the KMS key policy. This meant that there was a circular dependency - one not picked up by `terraform validate`. The policy couldn't be created until the …
> FIX: KMS Key(s)

- environments/common/elasticache/elasticache.tf
- environments/common/elasticache/locals.tf
I have:
- Added `dynamic` blocks for `log_delivery_configuration`.
- SLOWLOG requires Redis >=6.0
- Engine log requires Redis >=6.2
- Currently, we are using 5.0.6, but we may change upward in future so I'm leaving support for log delivery in the module.
> BAU: Fix log_delivery through dynamic blocks

- environments/common/elasticache/README.md
- environments/common/elasticache/elasticache.tf
- environments/common/elasticache/outputs.tf
- environments/common/elasticache/variables.tf
- environments/development/common/redis.tf
I have:
- Updated `aws_elasticache_replica_group` to use `num_node_groups` and `replicas_per_node_group`.
- Removed the `aws_elasticache_cluster.replica` resource.
- Removed unused outputs.
- The documentation was confusing: when using Redis in cluster mode, you need to use `num_node_groups` and `replicas_per_node_group`, to create shards with primary and read replicas respectively.
- The previous configuration was configured for Redis with cluster mode _disabled_, with fine-grained control of the replicas. However, we _don't_ wish to do this as we want automatic cluster failover.
> BAU: Fix ElastiCache cluster mode

- environments/common/ecr/README.md
- environments/common/ecr/ecr.tf
- environments/development/common/README.md
- environments/development/common/ecr.tf
I have:
- Made an output for the `repository_url` for the ECR module.
- Added an SSM parameter for this output.
- We need the applications to be able to fetch this using the AWS CLI, so that we can amend the CI for each application to put images into the new environments.
> BAU: Put ECR repo URL into SSM for consumption

- environments/development/common/README.md
- environments/development/common/kms.tf
- environments/development/common/rds.tf
- environments/development/common/redis.tf
I have:
- Added `aws_secretsmanager_secret`s for the Redis and Postgres connection strings.
- Added a KMS key to encrypt these secrets, with an alias.
- The ElastiCache Cluster and Postgres instance provide connection strings that will need to be given to the applications, so we should create these as AWS SecretsManager secrets that we can decrypt and pass to the application-level Terraform. ECS can fetch these values if passed to the secrets config.
> HOTT-3515: Add AWS Secrets Manager Secrets

- environments/common/ecr/README.md
- environments/common/ecr/ecr.tf
- environments/common/ecr/locals.tf
- environments/development/common/ecr.tf
I have:
- Changed the ECR module to create a repository for each of the applications;
- `admin`
- `backend`
- `duty-calculator`
- `frontend`
- `search-query-parser`
- After working on [HOTT-3513](https://github.com/trade-tariff/trade-tariff-frontend/pull/1503), I have come to the realisation that we do need a repository for each separate image. This is why I am getting the error 'EOF' from docker push commands.
- Whilst here, I've also changed resource names to `this`; they are in a module and there is only one of each resource type, so do not need special names, as they'll be referenced by the module call in each environment they are used in - this also conforms to Anton's best practices.
> BAU: Create ECR repository for each image

- environments/development/common/cloudwatch.tf
- environments/development/common/opensearch.tf
I have:
- Fixed bucket ACL creation failure
- Create OpenSearch service role
- We need the service-linked IAM role so that we can create the OpenSearch domain
- The buckets won't allow ACLs because of a change made to S3, the module
documentation isn't actually that good here and doesn't point this out,
but we need to specify the object ownership: https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/pull/226
> HOTT-3143: Fix OpenSearch/bucket creation

- environments/development/base/README.md
- environments/development/base/variables.tf
- environments/development/base/vpc.tf
I have:
- Enabled `single_nat_gateway`.
- Removed VPN gateway. 
- Simplified the variables as there's some that are just being set with defaults so not needed.
- We want a single NAT gateway in this configuration.
> BAU: Reconfigure VPC to use a single NAT gateway

- environments/common/security-group/security-group.tf
I have:
- Given the ECS security group egress the correct CIDR block to allow all egress traffic.
- We need public egress here so that the ECS tasks can reach ECR and pull the container images they need to start.
> BAU: Allow egress out from ECS

- environments/common/security-group/README.md
- environments/common/security-group/security-group.tf
- environments/common/security-group/variables.tf
[ci skip] because I don't want this to apply over the other open PRs
I have:
- Added an ingress rule on the ECS security group to allow HTTP traffic on 80 from the load balancer through to 8080 on ECS.
- Removed VPC CIDR block variable.
- We want HTTP traffic to be reach the applications from the load balancer, because the applications health checks are done by the load balancer - and can only be done over a non-TLS connection. This is the simplest way of digging ourselves out of that hole instead of making the applications terminate TLS.
- The egress rule that had the VPC CIDR block specified was wrong and needs to look like the below to work like the `ALLOW ALL` that we want it to:
```hcl
egress {
from_port        = 0
to_port          = 0
protocol         = "-1" …
```
> BAU: Allow HTTP traffic through to ECS from ALB

- environments/common/README.md
- environments/common/secret/.terraform.lock.hcl
- environments/common/secret/README.md
- environments/common/secret/main.tf
- environments/common/secret/outputs.tf
- environments/common/secret/variables.tf
- environments/common/secret/versions.tf
- environments/development/common/README.md
- environments/development/common/secrets.tf
- environments/development/common/variables.tf
[HOTT-3600](https://transformuk.atlassian.net/browse/HOTT-3600)
I have:
- Created a basic module to simplify creating SecetsManager Secrets.
- Moved secret resources to use the module.
- Added the backend 'secret key base' secret.
- The backend needs this secret but we want to keep it a secret rather than putting it into less secure service(s).
> HOTT-3600: Create Backend Secret(s)

- environments/development/common/README.md
- environments/development/common/locals.tf
- environments/development/common/secrets.tf
- environments/development/common/variables.tf
This PR forms a part of [HOTT-3227](https://transformuk.atlassian.net/browse/HOTT-3227).
_I have:_
- Added the `SECRET_KEY_BASE` secret resources for the Duty Calculator.
_I am doing this because:_
- This is a secret variable so needs to be configured through SecretsManager instead of given as plaintext to the service.
> HOTT-3227: Add Duty Calculator Secret

- environments/common/application-load-balancer/README.md
- environments/common/application-load-balancer/alb.tf
- environments/common/application-load-balancer/locals.tf
I have:
- Moved the list of services out into a local, with a map for each service, that contains its target group name, the priority of the rule, and the paths for the rule.
- Removed the target group rule resources and created a new one that builds rules using the `for_each`.
- We need the rest of the target groups at this stage so we can deploy the remaining applications easily.
- This makes editing the rules easier in the future if we need to add more paths.
> BAU: Create all remaining Target Groups

- environments/common/rds/README.md
- environments/common/rds/locals.tf
- environments/common/rds/rds.tf
- environments/common/rds/variables.tf
- environments/development/common/rds.tf
I have:
- Added `max_allocated_storage` to the RDS module.
- Set the allocated storage to a minimum of 10GB, and given a 2x scale factor up to a maximum of 20GB.
- When doing an initial dump and restore we found that the database size was over 7GB uncompressed, so the initial 5GB allocation was not enough.
> BAU: Enable Postgres Autoscaling

- environments/common/application-load-balancer/alb.tf
- environments/common/application-load-balancer/locals.tf
I have:
- Removed listener's default action of forwarding to frontend target groups.
- Added `dynamic` `condition` blocks to the listener rules to create the conditions dependant on the service mappings.
- Updated the mappings to each service.
- Split the backend target groups out between UK and XI.
- Adjusted the rule priorities.
- Some of the apps use host-based routing rules, so we'll need to create the listener conditions based on the service map and whether `paths` or `host` is specified for each service.
- Removed the default action to go to the frontend target group as it's not needed; we have a catch-all rule with the lowest priority. We could, alternatively, _not_ have the frontend rule, but it needs a target group - it's being created such that we're …
> BAU: Another Pass on Listener Rules

- environments/common/application-load-balancer/README.md
- environments/common/application-load-balancer/alb.tf
I have:
- Added a HTTP listener on port 80 that redirects to the HTTPS listener on 443.
- We should redirect HTTP on 80 to HTTPS on 443.
> BAU: Redirect HTTP to HTTPS

- environments/common/elasticache/README.md
- environments/common/elasticache/elasticache.tf
- environments/common/elasticache/outputs.tf
- environments/common/elasticache/variables.tf
- environments/common/elasticache/versions.tf
- environments/development/common/README.md
- environments/development/common/redis.tf
[ci skip] so as to not clobber the other PR I have open.
I have:
- Added more Redis.
- Switched to `for_each`ing the secrets as we'll have multiple Redis connection strings.
- We need multiple Redis instances (Redii?) as the services don't all use the same one. The frontend, backend(s) and the admin tool each expect their _own_ Redis to be available.
- Anywhere we are using the Redis connection string `redis-connection-string`, we'll have to update this to use the correct string for the specific instance we want.
> BAU: Create Multiple Redis Instances

- environments/common/acm/acm.tf
- environments/common/application-load-balancer/README.md
- environments/common/application-load-balancer/outputs.tf
- environments/development/common/README.md
- environments/development/common/acm.tf
- environments/development/common/route53.tf
I have:
- Added DNS record(s) for the origin (load balancer) to `origin.domain.tld`.
- We can reach the apps without going through the CDN later on.
> HOTT-3669: Create Origin DNS

- environments/common/acm/README.md
- environments/common/acm/acm.tf
- environments/common/acm/output.tf
- environments/common/acm/variables.tf
- environments/development/common/acm.tf
- environments/development/common/alb.tf
I have:
- Removed the zone lookup from the ACM module
- Added a `hosted_zone_id` input variable in the module
- We need the zone outside of the ACM module, so let's input the zone ID instead of looking up a zone, as this will fail when we pass in something that doesn't have a zone.
> HOTT-3669: Fix Hosted Zone IDs

- environments/common/security-group/security-group.tf
[ci skip]
I have:
- Added an `ingress` block on our security group to allow traffic on port 80.
- For our listener rule on 80 to work in redirecting traffic to 443, we need to allow the traffic in from 80 so we can deal with it at the listener.
> BAU: Allow HTTP traffic on 80 in from Internet

- environments/common/acm/README.md
- environments/common/acm/variables.tf
- environments/common/acm/versions.tf
- environments/development/common/README.md
- environments/development/common/acm.tf
- environments/development/common/alb.tf
- environments/development/common/cloudfront.tf
- environments/development/common/locals.tf
- environments/development/common/route53.tf
- environments/development/common/variables.tf
- environments/development/common/versions.tf
- environments/development/common/waf.tf
I have:
- Added the CDN
- Added the WAF to protect the CDN
- We have the origin, but we now need the CDN route so we have a protected and cacheable endpoint.
> HOTT-3670: Add CloudFront (and WAF)

- environments/development/common/secrets.tf
I have:
- Changed the key used to encrypt the `admin_bearer_token` secret.
- For some reason it was using the opensearch key, which is wrong. This meant the admin service couldn't start as it doesn't have access to that key.
> BAU: Use the correct key for secrets

- environments/development/common/README.md
- environments/development/common/cloudfront.tf
- environments/development/common/route53.tf
I have:
- Added an A record for the wildcarded origin subdomain.
- Added Route 53 A records for the required subdomains.
- Since we have two services that will be using host based routing, admin and signon, we'll want the origin to be accessible for them.
- We want to be able to hit these services at their respective paths, so we'll need A records.
> BAU: Add origin wildcard DNS record

- environments/common/rds/README.md
- environments/common/rds/data.tf
- environments/common/rds/locals.tf
- environments/common/rds/rds.tf
- environments/common/rds/variables.tf
- environments/development/common/README.md
- environments/development/common/rds.tf
[ci skip] because the changes are quite big.
I have:
- This PR makes significant change to the RDS module, in that it takes the connection string secret generation away from having to be created downstream. It does this by using a data source to fetch the secret created by RDS and extracting the password and parsing the inputs to build a connection string.
- I have also changed the name of the subnet group as it would otherwise clash with the new MySQL instance.
- The Signon service requires a small MySQL database, separate from the Postgres instance used by the backends.
- We need a connection string when we build out the RDS instances, so having the module handle this internally is a more useful abstraction.
> HOTT-3733: Create MySQL RDS Instance for Signon

- environments/common/application-load-balancer/alb.tf
- environments/common/rds/README.md
- environments/common/rds/data.tf
- environments/common/rds/locals.tf
- environments/common/rds/rds.tf
I have:
- Fix RDS password
- Shortened the deregistration delay on target groups
- The RDS password configuration had too much complexity and was just broken for some reason :(
- We don't want to have to wait 300 seconds for apps to deregister.
> BAU: Fix RDS password, shorten deregistration delay

- environments/common/application-load-balancer/alb.tf
- environments/common/application-load-balancer/locals.tf
[ci skip]
I have:
- Added `healthcheck_path` to the locals for the services.
- Changed the `path` of the `health_check` block to use this string from the locals.
- The signon service exposes it's healthcheck on `/healthcheck/live`. As we don't fork this, but simply pull `alphagov/signon` and apply basic `sed`/`echo` text patches, we can't edit to add our standard `/healthcheckz` path. In this case, we want to change the path of the health check we're doing through the target group.
> BAU: Set up healthcheck path dynamically

- environments/development/common/redis.tf
I have:
- Added `signon` to the list of Redis clusters to create.
- The signon tool needs its own Redis cluster.
> HOTT-3851: Create Redis cluster for Signon tool

- environments/production/applications/terragrunt.hcl
- environments/production/base/terragrunt.hcl
- environments/staging/applications/terragrunt.hcl
- environments/staging/base/terragrunt.hcl
- environments/staging/common/terragrunt.hcl
I have:
- Added base, common and applications folders and terragrunt config for staging and production
- Deploying services to staging and production for the first time
> HOTT-3852 - Add base, common and applications folder and terragrunt config for staging and production

- environments/development/applications/README.md
- environments/development/applications/dynamodb.tf
- environments/development/applications/locals.tf
- environments/staging/applications/README.md
- environments/staging/applications/dynamodb.tf
- environments/staging/applications/locals.tf
I have:
- Added DynamoDB lock tables for all applications.
- We need to enable Terraform state locking on the services as CI jobs may run in parallel across feature branches. This could cause state corruption, so we want to have locking in place to prevent this.
> HOTT-3884: Create lock tables for service TF

- environments/common/ecr/ecr.tf
I have:
- Reverted image_tag_mutability to MUTABLE temporarity until we update the build job to query repo to check if the tag already exists
> bau-ecr-mutable - Revert image_tag_mutability to MUTABLE

- environments/development/base/vpc.tf
I have:
- Renamed the `development` VPC to use hyphens instead of underscores.
- We should be consistent with our naming scheme across environments.
> BAU: Rename development VPC to align with standard

- environments/common/application-load-balancer/alb.tf
- environments/common/application-load-balancer/locals.tf
I have:
- Simplified target group names
- Removed blue/green target groups
- We no longer need the duplicated TGs
- The target group names don't need to be complex
> BAU: Simplify target groups

- environments/development/common/README.md
- environments/development/common/iam.tf
https://transformuk.atlassian.net/browse/HOTT-3136
We plan to reuse the same circle ci context for the development, staging and production
deployment workflows in the new world of serverless lambda functions.
The serverless function will manage the execution role of the specific lambda function as well as its deployment
and updates.
In terraform we need to create the shared s3 buckets (done elsewhere) and the users that will
orchestrate the deployment of each of the lambda functions in each of the accounts.
I have:
- This is required for us to be able to orchestrate deployments under different circle ci contexts for the serverless functions
> HOTT-3136: Adds serverless ci users and policies

- environments/development/common/README.md
- environments/development/common/secrets.tf
- environments/development/common/variables.tf
- environments/production/common/README.md
- environments/production/common/secrets.tf
- environments/production/common/variables.tf
- environments/staging/common/README.md
- environments/staging/common/secrets.tf
- environments/staging/common/variables.tf
I have:
- Added separate secrets for the uk and xi sync jobs
- This is necessary but also delineates clearly between the two worker environments
> BAU: Separate secrets for uk and xi workers

- environments/development/common/cloudfront.tf
Jira link
[HOTT-2803](https://transformuk.atlassian.net/browse/HOTT-2803)
I have:
- Set api docs cloudfront origin to s3 bucket
> Hott 2803 - Set api docs cloudfront origin to s3 bucket

- environments/development/common/cloudfront.tf
- environments/development/common/route53.tf
- environments/production/common/cloudfront.tf
- environments/production/common/route53.tf
- environments/staging/common/README.md
- environments/staging/common/cloudfront.tf
- environments/staging/common/route53.tf
I have:
- Added `signon` and `admin` subdomain aliases for the CDN.
- We need the CDN to have these configured so they can point at the origin correctly.
> BAU: Add missing CDN aliases

- environments/development/common/README.md
- environments/development/common/secrets.tf
- environments/development/common/variables.tf
- environments/production/common/README.md
- environments/production/common/secrets.tf
- environments/production/common/variables.tf
- environments/staging/common/README.md
- environments/staging/common/secrets.tf
- environments/staging/common/variables.tf
I have:
- Added Sentry dsn to development
- Added Sentry dsn to staging
- Added Sentry dsn to production
- These are needed for the admin apps to be able to log errors to sentry
> BAU: Adds Sentry DSN for admin globally

- environments/production/common/cloudfront.tf
[HOTT-2801](https://transformuk.atlassian.net/browse/HOTT-2801)
I have:
- Added `www` alias for the CDN.
- The current production environment requires it, so we'll want to keep it around.
> HOTT-2801: Keep www for Production

- environments/development/common/README.md
- environments/development/common/iam.tf
- environments/production/common/README.md
- environments/production/common/iam.tf
- environments/staging/common/README.md
- environments/staging/common/iam.tf
[HOTT-4007](https://transformuk.atlassian.net/browse/HOTT-4007)
I have:
- Added IAM roles for the breakglass user to be able to assume.
- The user on the management account works however we need role/policy for the individual accounts for breakglass use.
> HOTT-4007: Add Breakglass Roles

- environments/production/common/README.md
- environments/production/common/cloudfront.tf
[HOTT-2796](https://transformuk.atlassian.net/browse/HOTT-2796)
I have:
- Added a CloudFront distribution to sit in front of the reporting bucket.
- We're still blocked on the full extent of this ticket because of the migration requirements, but this is something that I can do to make sure we have everything set up for the hosted zone migration so that we can just _hit go_ when we want to use it.
> HOTT-2796: Create reporting CDN

- .circleci/config.yml
- environments/development/common/README.md
- environments/development/common/slack-notify.tf
- environments/production/applications/locals.tf
HOTT-4081
I have:
- Added terraform module to send aws cloudwatch alarm alerts to slack
-  To send slack alerts on triggered cloudwatch alarms
> HOTT-4081 - aws cloudwatch alarm alerts to slack

- environments/development/common/README.md
- environments/development/common/secrets.tf
- environments/development/common/variables.tf
- environments/production/common/README.md
- environments/production/common/secrets.tf
- environments/production/common/variables.tf
- environments/staging/common/README.md
- environments/staging/common/secrets.tf
- environments/staging/common/variables.tf
https://github.com/trade-tariff/trade-tariff-backend/pull/1562
I have:
- Added secrets for the differences emails to development
- Added secrets for the differences emails to staging
- Added secrets for the differences emails to production
- These are required to store PII for stakeholders that need to receive the differences emails
> HOTT-3359: Adds differences to emails secrets

- environments/common/application-load-balancer/alb.tf
I have:
- Removed the `frontend` listener rule from the LB.
- We should just use this as a default, the frontend can deal with 404s itself it's not dumb
> BAU: Remove Frontend Listener Rule

- environments/common/README.md
- environments/development/common/README.md
- environments/development/common/iam.tf
- environments/production/common/README.md
- environments/production/common/iam.tf
- environments/staging/common/README.md
- environments/staging/common/iam.tf
I have:
- Added appendix 5a ci user for development
- Added appendix 5a ci user for staging
- Added appendix 5a ci user for production
- This is needed to populate the appendix 5a data in the backend in the new world
> HOTT-4305: Adds appendix 5a configuration

- environments/development/common/README.md
- environments/development/common/cloudfront.tf
- environments/production/common/README.md
- environments/production/common/cloudfront.tf
- environments/staging/common/README.md
- environments/staging/common/cloudfront.tf
I have:
- Added dumps/reporting cdns for development
- Added dumps/reporting cdns for staging
- Added dumps cdn for production
- This enables users to use an easier navigation mechanism to traverse these objects and reduces our overheads in terms of credentials (see https://github.com/trade-tariff/trade-tariff-reporting)
> HOTT-4204: Adds CDNs for backups and reporting buckets

- environments/development/common/README.md
- environments/development/common/iam.tf
- environments/production/common/README.md
- environments/production/common/iam.tf
- environments/staging/common/README.md
- environments/staging/common/iam.tf
I have:
- Added reporting ci user to deploy the reporting SPA to development
- Added reporting ci user to deploy the reporting SPA to staging
- Added reporting ci user to deploy the reporting SPA to production
- This is required to migrate the reporting app to the CDNs managed by the new infrastructure
> HOTT-2796: Adds ci user to deploy reporting SPA

- environments/development/common/iam.tf
- environments/production/common/iam.tf
- environments/staging/common/iam.tf
I have:
- Added permission to enable distribution invalidation on the reporting ci user in development
- Added permission to enable distribution invalidation on the reporting ci user in staging
- Added permission to enable distribution invalidation on the reporting ci user in production
- This enables us to automate deployments
> HOTT-2796: Adds permission to invalidate the reporting distribution

- environments/production/common/README.md
- environments/production/common/ses.tf
I have:
- Removed the SES verification for the production domain
- We can't safely manage SES in production right now - this would break the
current production feedback by unverifying the identity in the old account
- This is blocking apply steps in production
> BAU: Removes SES in production

- environments/common/rds/README.md
- environments/common/rds/outputs.tf
- environments/development/common/README.md
- environments/development/common/rds.tf
- environments/development/common/sns.tf
- environments/development/common/versions.tf
[HOTT-4204](https://transformuk.atlassian.net/browse/HOTT-4204)
I have:
- Added SNS topic and event subscription for main database snapshots
- We need a trigger for the Lambda function so that we can fetch the export task ID and SourceArn of the snapshots
> HOTT-4204: Add SNS Topic and Event Subscription for RDS Snapshots

- environments/production/common/README.md
- environments/production/common/route53.tf
- environments/staging/common/README.md
- environments/staging/common/acm.tf
- environments/staging/common/outputs.tf
- environments/staging/common/route53.tf
- environments/staging/common/variables.tf
I have:
- Enables us to point a record at the apex to the API gateway we build for the FPO project
- Enables a clear separation between the sandbox URLs and the staging ones in the staging account
- Fixes an issue with SANs being validated in staging
> HOTT-4373: Adds separate sandbox zone

- environments/common/application-load-balancer/.terraform.lock.hcl
- environments/common/elasticache-redis/.terraform.lock.hcl
- environments/common/ses/.terraform.lock.hcl
- environments/development/base/.terraform.lock.hcl
- environments/development/common/.terraform.lock.hcl
- environments/production/applications/.terraform.lock.hcl
- environments/production/base/.terraform.lock.hcl
- environments/production/common/.terraform.lock.hcl
- environments/production/common/README.md
- environments/production/common/acm.tf
- environments/production/common/alb.tf
- environments/staging/applications/.terraform.lock.hcl
- environments/staging/base/.terraform.lock.hcl
- environments/staging/common/.terraform.lock.hcl
I have:
- Fixed an issue with ALM certs disappearing for origin
- This is required to get the apply step running on production
> BAU: Adds non-origin ACM cert for ALB

- environments/development/common/iam.tf
- environments/production/common/iam.tf
- environments/staging/common/iam.tf
I have:
- Given severless user access to the ECR URL SSM parameters
- The serverless user needs to be able to pull the image for Docker-in-Lambda setups
> BAU: Allow Serverless user SSM access

- environments/production/common/ecr.tf
I have:
- Added `ecr:DescribeImages` to ECR policy.
- The serverless user needs this permission.
> BAU: Allow DescribeImages on ECR

- environments/production/common/ecr.tf
I have:
- Added access to ECR repositories to the serverless-lambda-ci in development
- Added access to ECR repositories to the serverless-lambda-ci in staging
- Added access to ECR repositories to the serverless-lambda-ci in production
- This is required to enable us to deploy with ECR repos
> HOTT-4367: Enable ECR access to circle ci context users

- environments/common/cloudfront-auth.js.tpl
- environments/development/common/README.md
- environments/development/common/cloudfront.tf
- environments/development/common/locals.tf
- environments/development/common/variables.tf
- environments/production/common/README.md
- environments/production/common/cloudfront.tf
- environments/production/common/locals.tf
- environments/production/common/variables.tf
- environments/staging/common/README.md
- environments/staging/common/cloudfront.tf
- environments/staging/common/locals.tf
- environments/staging/common/variables.tf
I have:
- Added basic auth to the backups CDN using CloudFront functions
- We need at least _some_ protection on these as they're literally database dumps
> HOTT-4423: Add Basic Auth to Backups

- environments/common/security-group/.terraform.lock.hcl
- environments/development/common/README.md
- environments/development/common/acm.tf
- environments/development/common/iam.tf
- environments/production/common/README.md
- environments/production/common/acm.tf
- environments/production/common/iam.tf
- environments/staging/common/README.md
- environments/staging/common/acm.tf
- environments/staging/common/iam.tf
I have:
- This is required to have custom domains for our FPO lambda
> HOTT-4106: Adds ACM certs for London and update lambda deployment permissions

- environments/production/common/iam.tf
- environments/staging/common/iam.tf
I have:
- Added "iam:CreateServiceLinkedRole" for lambda deployment user in staging
- Added "iam:CreateServiceLinkedRole" for lambda deployment user in production
- This was missed in a previous PR and is essential for creating custom domains
> BAU: Adds "iam:CreateServiceLinkedRole" for lambda deployment user

- environments/development/common/iam.tf
- environments/production/common/iam.tf
- environments/staging/common/iam.tf
I have:
- Added permissive ability to read information about all zones
- Preserved restriction on mutating actions for zones
- This is required to enable the lambda deployment user to list zones
> HOTT-4427: Enable permissive reads but restricted writes

- environments/development/common/cloudfront-policy.tf
- environments/production/common/cloudfront-policy.tf
- environments/staging/common/cloudfront-policy.tf
I have:
- Removed the override of the `Content-Security-Policy` header in CloudFront response headers policy.
- The frontend loads a lot of inline items which break when this header is set, so its easier right now to just unset this.
> BAU: Unset Content-Security-Policy override

- environments/production/common/ecr.tf
I have:
- Added `ecr:DescribeRepositories` to the ECR policy for the Lambda deployments IAM user.
- It needs this permission to build and push to ECR.
> BAU: Add DescribeRepositories for Lambda IAM User

- environments/production/common/opensearch.tf
I have:
- Altered instance types in opensearch production cluster
- This makes us conform to the current active production cluster
> BAU: Upgrade opensearch cluster instance types

- environments/development/common/rds.tf
I have:
- Altered development env to use a t3.medium
- To avoid congestion in dev
> BAU: Bump development RDS instance sizing

- environments/production/common/README.md
- environments/production/common/ses.tf
I have:
- Added SES verified identity for the base domain
- This is required to send emails out of the production account and will automatically propagate verified identities in production when we switchover the base domain
> BAU: Adds SES verified identities

- environments/production/common/README.md
- environments/production/common/acm.tf
- environments/production/common/alb.tf
- environments/production/common/locals.tf
- environments/production/common/route53.tf
I have:
- Altered the production origin match the dev/staging one
- This is required to have a consistent means of terminating the origin which doesn't load the main certificate which is a mismatch with the ALBs host address
> BAU: Make origin/certificate/ALB record match

- environments/development/common/opensearch.tf
I have:
- Altered instance type of opensearch cluster instances in development
- This will fix an issue with system memory in the development cluster which is breaking our ability to generate opensearch indexes (see https://engine-le.sentry.io/issues/4679200734/?alert_rule_id=12852327&alert_type=issue&environment=development&notification_uuid=12ab3386-a130-4828-bfea-b1049f9c1c55&project=5557005&referrer=slack)
> HOTT-4365: Alter minimum-required opensearch cluster instance types

- environments/common/rds/README.md
- environments/common/rds/data.tf
- environments/common/rds/locals.tf
- environments/common/rds/outputs.tf
- environments/development/common/README.md
- environments/development/common/rds.tf
- environments/production/common/README.md
- environments/production/common/rds.tf
- environments/staging/common/README.md
- environments/staging/common/rds.tf
[`HOTT-2949`](https://transformuk.atlassian.net/browse/HOTT-2949)
I have:
- Added a read-only connection string secret for the backend postgres.
- We want to have a read-only connection for everything except the admin API.
> HOTT-2949: Add Read-Only Backend Postgres Connection String

- environments/development/common/README.md
- environments/development/common/waf.tf
- environments/production/common/README.md
- environments/production/common/waf.tf
- environments/staging/common/README.md
- environments/staging/common/waf.tf
See https://github.com/trade-tariff/trade-tariff-platform-terraform-modules/pull/51
I have:
- Bumps WAF module in development
- Bumps WAF module in staging
- Bumps WAF module in production
- This is required because we've got a WAF rule that is applying to the admin app in the new world (where there wasn't a WAF/CDN before)
- We're trying to post large markdown documents to the admin backend and are coming into a WAF block
> HOTT-4670: Bumps waf module

- environments/development/common/cloudfront.tf
- environments/production/common/cloudfront.tf
- environments/staging/common/cloudfront.tf
I have:
- Added a rule to not cache `/xi/api/v2/green_lanes/*`
- This section of the API should not be cached as it's not publically accessible.
> BAU: Don't Cache /xi/api/v2/green_lanes/*

- environments/common/ecr/locals.tf
https://transformuk.atlassian.net/browse/FPO-128
I have:
- Added ECR repo in production for the fpo hub
- This is needed as part of dockerising the FPO hub application
> FPO-128: Adds ECR repo for the fpo hub

- environments/common/application-load-balancer/alb.tf
- environments/common/application-load-balancer/locals.tf
- environments/development/common/cloudfront.tf
- environments/production/common/cloudfront.tf
- environments/staging/common/cloudfront.tf
Ran the infrastructure smoke tests to validate changing the rules
I have:
- Added CDN alias
- Added ALB listener rule to match the backend and frontend hub routes
- This is required so we can have release notes for the backend hub and also to expose the frontend hub publicly to our hub developers
> FPO-133: Adds ALB support for hub

- environments/development/common/locals.tf
- environments/production/applications/locals.tf
- environments/staging/applications/locals.tf
- environments/staging/common/locals.tf
I have:
- Adds SSM parameter for ECR url in development
- Adds SSM parameter for ECR url in staging
- Adds dynamodb locks for staging hub apps
- Adds dynamodb locks for production hub apps
- We need lock tables for staging and production
- We need ECR SSM parameters for development and staging
> FPO-133: Adds locks and SSM params for FPO developer hub

- environments/development/applications/README.md
- environments/development/applications/dynamodb.tf
- environments/production/applications/README.md
- environments/production/applications/dynamodb.tf
- environments/staging/applications/README.md
- environments/staging/applications/dynamodb.tf
https://transformuk.atlassian.net/browse/FPO-132
I have:
- Added dynamo db table for CustomerApiKeys in development
- Added dynamo db table for CustomerApiKeys in staging
- Added dynamo db table for CustomerApiKeys in production
- These are needed for the FPO developer hub in order to manage keys for accessing the inference apis
- We've optimised for the queries that we're going to do by using the CustomerId (e.g. yodel) as the range column so that when we filter by the keys that belong to a specific customer they are colocated and we don't have to hit multiple dynamodb nodes.
- We've added a tag to make billing easier
- We've opted for pay as you go billing since we do not anticipate the need for lots and lots of updates to this table
> FPO-132: Add dynamodb tables for FPO Developer Hub

- environments/development/common/cloudfront-policy.tf
- environments/staging/common/cloudfront-policy.tf
I have:
- Altered the CDN config for Dev and Staging to allow Authenticated CORS API requests
- It will allow the API Docs api client to access the api's from a browser
- I'm not changing production at this time because we don't require access to the production version of the API yet and it will be good to give chance to ensure the allow listing of headers doesn't have any unintended consequences
> GL-133 Allow access control headers from the browser

- environments/development/applications/dynamodb.tf
- environments/production/applications/dynamodb.tf
- environments/staging/applications/dynamodb.tf
I have:
- Renamed CustomerId to FpoId
- This is required to reflect the change in the FPO hub backend https://github.com/trade-tariff/trade-tariff-dev-hub-backend/pull/10
> BAU: Rename CustomerId to FpoId to avoid confusion with ApiGateway concepts

- environments/development/common/cloudfront.tf
- environments/production/common/cloudfront.tf
- environments/staging/common/cloudfront.tf
Jira link
https://transformuk.atlassian.net/browse/HOTT-4950
I have:
- Changed cache policy for database backups.
- Database backups shouldn't be cached.
> Changed cache policy for backup_cdn module

- environments/development/common/README.md
- environments/development/common/cloudfront.tf
- environments/development/common/secrets.tf
- environments/development/common/variables.tf
- environments/production/common/README.md
- environments/production/common/secrets.tf
- environments/production/common/variables.tf
- environments/staging/common/README.md
- environments/staging/common/secrets.tf
- environments/staging/common/variables.tf
I have:
- Adds hub backend secrets to development
- Adds hub backend secrets to staging
- Adds hub backend secrets to production
- These are required to enable associating API keys with usage plans (effectively enabling these keys in the relevant api gateway) and to enable consistent AES encryption of secrets
> FPO-157: Adds hub backend secrets

- environments/development/common/README.md
- environments/development/common/secrets.tf
- environments/development/common/variables.tf
- environments/production/common/README.md
- environments/production/common/secrets.tf
- environments/production/common/variables.tf
- environments/staging/common/README.md
- environments/staging/common/secrets.tf
- environments/staging/common/variables.tf
FPO-158
I have:
- Adds sentry dsns for hub in development, staging and production
- These are required to enable reporting exceptions in the dev hub to sentry
> FPO-158: Adds sentry DSN secrets

- .github/pull_request_template.md
- environments/development/applications/dynamodb.tf
- environments/production/applications/dynamodb.tf
- environments/staging/applications/dynamodb.tf
FPO-143
I have:
- Enable PITR recovery for CustomerApiKeys in development
- Enable PITR recovery for CustomerApiKeys in staging
- Enable PITR recovery for CustomerApiKeys in production
- These are required for automating the recovery of secrets configuration in the event of DR scenario
> FPO-143: Enable PITR on CustomerApiKeys

- environments/development/common/README.md
- environments/development/common/cloudfront.tf
- environments/development/common/s3.tf
- environments/production/common/README.md
- environments/production/common/cloudfront.tf
- environments/production/common/s3.tf
- environments/staging/common/README.md
- environments/staging/common/cloudfront.tf
- environments/staging/common/s3.tf
FPO-143
I have:
- Adds bucket and CDN configuration for tech-docs in development
- Adds bucket and CDN configuration for tech-docs in staging
- Adds bucket and CDN configuration for tech-docs in production
- This is required to enable us to deploy a static site using govuk templates https://github.com/alphagov/tdt-documentation/
> FPO-143: Adds tech docs bucket and CDN

- environments/development/common/README.md
- environments/development/common/cloudfront-policy.tf
- environments/development/common/cloudfront.tf
- environments/production/common/README.md
- environments/production/common/cloudfront-policy.tf
- environments/production/common/cloudfront.tf
- environments/staging/common/README.md
- environments/staging/common/cloudfront-policy.tf
- environments/staging/common/cloudfront.tf
BAU
I have:
- Removed WAF from tech-docs CDN
- Make sure we give permission to the tech-docs cloudfront distribution to have access to the tech-docs bucket
- This isn't required and was a copy/paste error
> BAU: Adjust IAM permissions in tech-docs CDN

- environments/development/common/README.md
- environments/development/common/cloudfront.tf
- environments/development/common/iam.tf
- environments/production/common/README.md
- environments/production/common/cloudfront.tf
- environments/production/common/iam.tf
- environments/staging/common/README.md
- environments/staging/common/cloudfront.tf
- environments/staging/common/iam.tf
FPO-143
I have:
- Added a tech-docs deployment user
- Disabled cache policy on tech-docs CDN so we no longer need to manually invalidate all the time
- This is required to deploy to the tech-docs bucket
> FPO-143: Adds tech-docs deployment user

- environments/production/common/README.md
- environments/production/common/route53.tf
- environments/staging/common/README.md
- environments/staging/common/acm.tf
- environments/staging/common/iam.tf
- environments/staging/common/outputs.tf
- environments/staging/common/route53.tf
- environments/staging/common/variables.tf
FPO-170
I have:
- Removed sandbox zone, certificates, references, etc
- These are now redundant since we're moving into private beta
> FPO-170: Remove now-defunct sandbox zone

- environments/development/common/README.md
- environments/development/common/iam.tf
- environments/development/common/secrets.tf
- environments/development/common/variables.tf
- environments/production/common/README.md
- environments/production/common/iam.tf
- environments/production/common/secrets.tf
- environments/production/common/variables.tf
- environments/staging/common/README.md
- environments/staging/common/iam.tf
- environments/staging/common/secrets.tf
- environments/staging/common/variables.tf
FPO-139
I have:
- Adds sentry dsn secret for fpo-search in development
- Adds sentry dsn secret for fpo-search in staging
- Adds sentry dsn secret for fpo-search in production
- These are required to configure sentry in the FPO-search lambda using serverless/cloudformation
> FPO-139: Adds sentry secrets for FPO-search

- environments/development/common/cloudfront.tf
- environments/production/common/cloudfront.tf
- environments/staging/common/cloudfront.tf
BAU
I have:
- Altered api docs policy not to cache
- We deploy at any point in the day and we just want the updated documentation
> BAU: Stop caching API docs

- environments/development/common/README.md
- environments/development/common/iam.tf
- environments/development/common/secrets.tf
- environments/development/common/slack-notify.tf
- environments/development/common/variables.tf
- environments/production/common/README.md
- environments/production/common/iam.tf
- environments/production/common/secrets.tf
- environments/production/common/slack-notify.tf
- environments/production/common/variables.tf
- environments/staging/common/README.md
- environments/staging/common/iam.tf
- environments/staging/common/secrets.tf
- environments/staging/common/slack-notify.tf
- environments/staging/common/variables.tf
FPO-183
I have:
- Replicated slack-notify lambda into lower environments
- Fixed super noisy alarms that lead to signal fatigue
- Extended lambda deployment user IAM policy to be able to create alarms and have them register against the slack topic
- People have ended up muting the channel since we were getting lots of
notifications for what are ultimately acceptable request times
- The original times would be comfortable low water marks but not high water marks
- For validation before we make changes straight to production
> FPO-183: Reduce alerts in slack and extend to lower environments

- environments/development/common/slack-notify.tf
- environments/production/common/slack-notify.tf
- environments/staging/common/slack-notify.tf
FPO-183
I have:
- Added environment to the description of every alarm
- Altered treat missing data to `notBreaching`
- I moved us to `notBreaching` to avoid flipping okay notifications when we transition from no data to having data
- It is a bit maddening not knowing which environment an alarm originates from
> FPO-183: Fixes issue with INSUFFICIENT_DATA

- environments/development/common/iam.tf
- environments/production/common/iam.tf
- environments/staging/common/iam.tf
BAU
I have:
- Added ability for the lambda deployment user to attach/detach iam role policies
- This is needed to deploy the status-checks serverless function
> BAU: Allow attaching/detaching role policies on lambda deployment user

- environments/development/common/README.md
- environments/development/common/iam.tf
- environments/development/common/variables.tf
- environments/production/common/README.md
- environments/production/common/iam.tf
- environments/production/common/variables.tf
- environments/staging/common/README.md
- environments/staging/common/iam.tf
- environments/staging/common/variables.tf
FPO-184
I have:
- Added a user to deploy our status checks page
- This is needed for isolated permissions to push to our status-checks s3 bucket
> FPO-184: Adds user to deploy status-checks page

- environments/development/common/cloudfront.tf
- environments/production/common/cloudfront.tf
- environments/staging/common/cloudfront.tf
OTT-224
I have:
- Disabled caching in the reporting bucket CDN
- To avoid having index.html getting a list result that is cached
> OTT-224: Disable caching in the reporting bucket

- environments/development/common/README.md
- environments/development/common/iam.tf
- environments/development/common/secrets.tf
- environments/development/common/variables.tf
- environments/production/common/README.md
- environments/production/common/iam.tf
- environments/staging/common/README.md
- environments/staging/common/iam.tf
FPO-201
I've populated the circle ci context secret var for the pem offscreen. I've also created contexts for each of the environments for configuration with the AWS credentials we need to enable CI workflows to happen
I have:
- Added new user for fpo model ci tasks
- Added permissions for the development user to read the pem private key
- Added cross account permissions for access to production model bucket
- This is required to enable our production bucket to store the full history of released/development model derivations
> FPO-201: Cross Account IAM permissions and secrets for training models

- .circleci/config.yml
- environments/development/applications/README.md
- environments/development/extra-regions/us-east-1/README.md
- environments/development/extra-regions/us-east-1/data.tf
- environments/development/extra-regions/us-east-1/locals.tf
- environments/development/extra-regions/us-east-1/outputs.tf
- environments/development/extra-regions/us-east-1/security_groups.tf
- environments/development/extra-regions/us-east-1/terragrunt.hcl
- environments/development/extra-regions/us-east-1/versions.tf
- environments/development/extra-regions/us-east-1/vpc.tf
- environments/staging/base/vpc.tf
FPO-201
I have:
- Added VPC for us-east-1
- The plan for the moment is that this will be configured for use by the FPO
search training instance. The kinds of AMI/instance type we want to use right
now for this are only available in this region.
> FPO-201: Adds dedicated VPC for extra-region us-east-1

- environments/development/common/iam.tf
- environments/production/common/s3.tf
- environments/staging/common/iam.tf
FPO-201
I have:
- Added explicit permissions to enable production model bucket access for the dev and staging ci user
- Added permissions for ci user to create, tag, delete, etc, ec2 instances and amis
- These are needed for CI to work
> FPO-201: Explicitly enable access to the production model bucket

- environments/development/common/README.md
- environments/development/common/secrets.tf
- environments/production/common/README.md
- environments/production/common/secrets.tf
- environments/staging/common/README.md
- environments/staging/common/secrets.tf
FPO-185
I have:
- Removed redundant usage plan secrets
- These are no longer required
> FPO-185: Removes redundant references to a single usage plan

- modules/common/application-load-balancer/locals.tf
[GL-502](https://transformuk.atlassian.net/browse/GL-502)
I have:
- Added target group and listener rule for `beta.*` for beta frontend.
- We want to capture traffic for the beta frontend application.
> GL-502: Add Frontend Beta Target

- environments/development/common/cloudfront.tf
- environments/production/common/cloudfront.tf
- environments/staging/common/cloudfront.tf
I have:
- Added the `beta.` alias for all CDNs.
- I missed this and traffic won't route correctly without it.
> GL-502: Add CDN alias for beta app

- modules/common/ecr/locals.tf
BAU
I have:
- Added terraform repo for terraform docker images
- This is required since the current ECR repo is named after an image not a repo
> BAU: Adds tariff-terraform repo

- environments/development/common/slack-notify.tf
- environments/production/common/slack-notify.tf
- environments/staging/common/slack-notify.tf
- modules/common/application-load-balancer/outputs.tf
BAU
I have:
- Filter specific alarms by their target group
- This gives us a clearer picture on which apps are affected
> BAU: Filter alarms by target group

- environments/production/common/iam.tf
FPO-233
I have:
- Added cross-account permissions to manage the model bucket to the garbage collection lambda execution role
- This is needed to enable running this lambda in dev/staging and production accounts
> FPO-233: Adds permissions to FPO GC execution roles to the model bucket

- environments/production/common/iam.tf
BAU
I have:
- Fixed broken references to what were non-existing roles
- These roles had to be created to be referenced
- These references needed to be the exact arns of the existing roles
- Since the exact roles included the account stage it made more sense to just create them explicitly
> BAU: Roles need to be exact and they need to exist

- environments/development/common/locals.tf
GL-732
I have:
- Added an ECR repository for restoring database backups in development
- This is required for the replication lambda
> GL-732: Adds development ECR repo for replication lambda

- environments/development/common/cloudfront.tf
- environments/production/common/cloudfront.tf
- environments/staging/common/cloudfront.tf
- modules/common/application-load-balancer/locals.tf
- modules/common/application-load-balancer/variables.tf
FPO-324
I have:
- Added CDN aliases to cloudfront for tea.* for dev, staging and production
- Added ALB service target group/listener rules for tea.*
- Adjusted priority rules to get the tea. rule in the right position
- This is required to enable us to deploy the ECS service for the commodi-tea application
> FPO-324: Adds cloudfront aliases for commodi-tea

- environments/development/common/locals.tf
- environments/staging/common/locals.tf
- modules/common/ecr/locals.tf
BAU
I have:
- Added ECR repo to production
- Added SSM parameter pointing at the repo in production
- Added SSM parameter pointing at the repo in staging
- Added SSM parameter pointing at the repo in development
- This is needed for the commodi-tea application in each environment
> BAU: Adds ECR repo for the commodi-tea application

- environments/development/applications/locals.tf
- environments/development/common/README.md
- environments/development/common/locals.tf
- environments/development/common/secrets.tf
- environments/production/applications/locals.tf
- environments/production/common/README.md
- environments/production/common/secrets.tf
- environments/staging/applications/locals.tf
- environments/staging/common/README.md
- environments/staging/common/locals.tf
- environments/staging/common/secrets.tf
- modules/common/application-load-balancer/locals.tf
- modules/common/ecr/locals.tf
OTT-384
I have:
- Removed unused ALB target groups and listeners
- `search_query_parser` has gone away since we're not doing beta search anymore
- `backend_xi`/ `backend_uk` gone away for the same reason since this was a holepunch to the backend just for beta search
> OTT-384: Removes unused target groups/listener rules

- environments/production/applications/locals.tf
BAU
I have:
- Added tea application lock in dynamodb in production
- This is required to constrain the apply step for the commodi-tea application
> BAU: Creates a tea lock in production

- modules/common/ecr/ecr.tf
- modules/common/ecr/locals.tf
OTT-398
I've ran these rules in the ECR test rule simulator for the admin repo and am comfortable that these are working as expected
I have:
- Added a comment explaining some of the hidden aspects of our lifecycle rules
- Altered the existing rules to move us to a count-oriented approach
- Altered the existing rules to reflect the types of deployment we have (manual, continuous)
- Date-oriented rotations don't fit our model of infrequently deployed applications (think duty calculator/signon)
- The rules themselves weren't super clear about what the intent was
- And weren't customisable
> OTT-398: Root and branch review of the ECR lifecycle rules

- environments/staging/applications/locals.tf
BAU
I have:
- Added `tea` application to staging
- This is needed to deploy the commodi-tea app to staging
> BAU: Adds tea to applications in staging

- .tool-versions
- environments/development/common/.terraform.lock.hcl
- environments/development/common/README.md
- environments/development/common/acm.tf
- environments/development/common/cognito.tf
- environments/development/common/rds.tf
- environments/development/common/variables.tf
- environments/production/common/README.md
- environments/production/common/acm.tf
- environments/production/common/cognito.tf
- environments/production/common/rds.tf
- environments/production/common/variables.tf
- environments/staging/common/README.md
- environments/staging/common/acm.tf
- environments/staging/common/cognito.tf
- environments/staging/common/rds.tf
- environments/staging/common/variables.tf
- modules/common/rds/rds.tf
- modules/common/rds/variables.tf
[FPO-335](https://transformuk.atlassian.net/jira/software/projects/FPO/boards/116?selectedIssue=FPO-335)
I have:
- Added a new resource `aws_db_parameter_group` named `tea` to the codebase.
- Added `parameter_group_name` to `aws_db_instance` resource.
- Added the subdomain name in the ACM `subject_alternative_names`.
- Removed the resource server configuration and updated client OAuth configs.
- Altered staging and production configurations to include the `aws_db_parameter_group` resource, but commented it out for now.
- We need to set up secure user authentication and authorization for the commodi-tea application using Amazon Cognito
- The `postgres16-with-md5-password-encryption` parameter group was present in the AWS development console but missing from the …
> FPO-335: Create Tea Cognito User Pool and add DB Parameter Group

- environments/development/common/cloudfront.tf
- environments/production/common/cloudfront.tf
- environments/staging/common/cloudfront.tf
[`GL-603`](https://transformuk.atlassian.net/browse/GL-603)
I have:
- Removed the CDN caching exception for `/xi/api/v2/green_lanes/*` routes.
- Currently there is an exception in the CDN config for green lanes api endpoints to avoid those being cached (because we don’t want the CDN to cache an authenticated response, then serve it to a non-authenticated user). We should instead remove the exception and start caching the green lanes endpoints.
> GL-603: Remove GL Caching Exception

- environments/development/applications/.terraform.lock.hcl
- environments/development/common/rds.tf
- environments/production/common/rds.tf
- environments/staging/common/rds.tf
- modules/rds/rds.tf
- modules/rds/variables.tf
I have: 
- Removed the "postgres16-with-md5-password-encryption" parameter group: This custom parameter group has been deleted as it is no longer needed.
- Updated commodi-tea DB instances: That instance has been reassigned to use the default default.postgres16 parameter group instead of the custom one.
- Updated Terraform configuration: The Terraform configuration has been updated to reflect the removal of the postgres16-with-md5-password-encryption parameter group resource.
After discussing with Will, I found out that the custom parameter group he created (postgres16-with-md5-password-encryption) was no longer needed so i.
> Delete pg name

- environments/development/common/README.md
- environments/development/common/cognito.tf
- environments/production/common/cognito.tf
- environments/staging/common/cognito.tf
I have:
- Added `username_attributes`, `auto_verified_attributes`, and `client_identity_providers`.
- Removed `alias_attributes`.
- Altered ...
- Primary User Identification: By setting username_attributes = ["email"], we ensure that users can log in using their email address, simplifying the login process.
- Automatic Email Verification: Adding auto_verified_attributes = ["email"] allows for automatic verification of users' email addresses.
- Hosted UI Support: The inclusion of client_identity_providers = ["COGNITO"] enables the use of the Cognito-hosted UI.
- Removing alias_attributes reduces the potential for conflicts with username_attributes
> Add Email-Based Login, Auto Verification, and Enable Hosted UI

- environments/development/common/README.md
- environments/development/common/cognito.tf
- environments/production/common/cognito.tf
- environments/staging/common/cognito.tf
BAU
I have:
- Added localhost as a callback url for the development tea user pool
- Added /auth/redirect as a callback url for the pool in all environments
- Added support for new secret needed by express-openid-connect
- This enables redirects in the auth middleware in the localhost/development environment
- This is required secret configuration to get the middleware working (see https://github.com/trade-tariff/trade-tariff-commodi-tea/pull/21)
> BAU: Get tea user pool working

- environments/development/common/iam.tf
FPO-404
I have:
- Added permission to describe keypairs
- This is needed for the ci user
> FPO-404: Adds permissions to describe keypair

- environments/production/common/README.md
- environments/production/common/iam.tf
- environments/production/common/secrets.tf
- environments/staging/common/README.md
- modules/secret/main.tf
- modules/secret/variables.tf
OTT-431
I have:
- Added secret for the download_cds_files to email list
- Made the secret string value optional so we can manage our secret versions ourselves
- This should reduce the effort to manage this list of TO_EMAILS that is consumed by the circle ci workflow, here: https://github.com/trade-tariff/download-CDS-files
> OTT-431: Adds secret for cds downloader process

- environments/development/common/cognito.tf
- environments/production/common/cognito.tf
- environments/production/common/secrets.tf
- environments/staging/common/cognito.tf
- modules/secret/main.tf
- modules/secret/variables.tf
[FPO-425](https://transformuk.atlassian.net/jira/software/projects/FPO/boards/116?selectedIssue=FPO-425)
I have:
- Fixed the invalid count argument in `aws_secretsmanager_secret_version` by updating the conditional check for var.secret_string (!= null to == null ? 0 : 1).
- Updated the Cognito user pool schema to include `name`, `family_name`, and `email `attributes as required fields.
- The secrets manager configuration was causing an error during the plan phase due to improper handling of the `count` argument when `secret_string` was `null`.
- We needed the `name` (first name) and `family_name` (last name) attributes in the Cognito user pool to support user data for a leaderboard feature in our app.
> Fpo 425 update cognito user pool

- environments/development/common/rds.tf
- environments/production/common/rds.tf
- environments/staging/common/rds.tf
I have: 
- Updated the PostgreSQL engine version from 13.13 to 13.15 in the Terraform configuration.
- AWS RDS no longer supports PostgreSQL version 13.13, and the lowest available version is 13.15. This mismatch was causing version-related errors during RDS instance updates.
> Fix rds engine version error. Upgrade from 13.13 to 13.15

- environments/development/common/README.md
- environments/development/common/acm.tf
- environments/development/common/alb.tf
- environments/development/common/cloudfront.tf
[`HMRC-237`](https://transformuk.atlassian.net/browse/HMRC-237)
I have:
- Added new ALB and CDN for preview apps.
- We are switching away to preview apps in lower environments, which necessitates creating many of the target groups, listener rules, and assorted load balancer infrastructure at deploy-time.
- To minimise disruption in these environments, a new ALB and CDN are needed so we can test this setup alongside the current environment.
> HMRC-237: Preview apps ALB

- environments/development/common/waf.tf
- environments/production/common/waf.tf
- environments/staging/common/waf.tf
I have:
- Updated the WAF logging configuration to drop all logs from the `NoUserAgent_Header` rule that are bypassed with a `COUNT` action.
- We get a lot of requests to the service where users have not set a user agent header, meaning we get a lot of noise in our log group.
> HMRC-366: Reduce noise in WAF log group

- environments/development/common/alb.tf
- environments/production/common/alb.tf
- environments/staging/common/alb.tf
HMRC-490 
I have:
- Removed the routes to `beta.*` as this is not used.  Commented out in case we want it back in the future.  All `beta.*` traffic thus is routed to the main production app for now.
Beta is not used at the moment.
> HMRC-490 Remove beta routes

- environments/development/common/cognito.tf
- environments/production/common/cognito.tf
- environments/staging/common/cognito.tf
HMRC-582
I have:
- Altered the Commodi-tea cognito configuration to disallow user registration. 
- Users should be invited rather than being able to sign themselves up.
> HMRC-582: Disable user registration on Commodi-tea

- environments/production/common/variables.tf
- environments/staging/common/variables.tf
BAU
I have:
- Altered rpm limit on the staging waf from 5000 to 2500
- Altered rpm limit on the production waf from 5000 to 2500
- This is a more sensible configuration based on looking at API usage
> BAU: Configure a more aggressive rate limit in staging and production

- environments/production/common/cloudfront.tf
HMRC-635
We can cache more than we are in Cloudfront.  This PR adds:
```
/images
/packs
/assets
```
at a TTL of a day, plus
```
/uk/api
/xi/api
```
at 30 minutes
> HMRC-635 Add more content to CF Cache

- .circleci/config.yml
- environments/development/common/alb.tf
- environments/development/common/cloudwatch.tf
- environments/development/common/versions.tf
- environments/production/common/README.md
- environments/production/common/cloudwatch.tf
- environments/production/common/versions.tf
- environments/staging/common/alb.tf
- environments/staging/common/cloudwatch.tf
- environments/staging/common/versions.tf
I have:
- This is required to separate out the backend api requests from the frontend
- The lifecycle policy can't have both days and expired_object_delete_marker and these contradictory values must have changed in how they behind in the AWS apis (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_lifecycle_configuration)
> HMRC-657: Adds route to uk and xi backend apps

- environments/production/common/alb.tf
BAU
I have:
- Revert separation of the backend and frontend
- This is required to debug a confusing error in the frontend
> BAU: Debug 500s

- environments/development/common/README.md
- environments/development/common/variables.tf
- environments/production/common/README.md
- environments/production/common/variables.tf
- environments/staging/common/README.md
- environments/staging/common/variables.tf
BAU
I have:
- Reduced WAF limits to 400 requests per minute in development
- Reduced WAF limits to 400 requests per minute in staging
- Reduced WAF limits to 400 requests per minute in production
- This is required until we review our rate limit rules
> BAU: Set the rate limit to match what was configured in the UI

- .pre-commit-config.yaml
- environments/development/applications/versions.tf
- environments/development/base/versions.tf
- environments/development/common/README.md
- environments/development/common/ecr.tf
- environments/development/common/redis.tf
- environments/development/common/variables.tf
- environments/development/common/versions.tf
- environments/production/applications/versions.tf
- environments/production/base/versions.tf
- environments/production/common/README.md
- environments/production/common/ecr.tf
- environments/production/common/redis.tf
- environments/production/common/variables.tf
- environments/production/common/versions.tf
- environments/staging/applications/versions.tf
- environments/staging/base/versions.tf
- environments/staging/common/README.md
- environments/staging/common/ecr.tf
- environments/staging/common/redis.tf
- environments/staging/common/variables.tf
- environments/staging/common/versions.tf
- modules/ecr/ecr.tf
- modules/ecr/variables.tf
I have:
- Added `default_tags` for all stacks.
- Lots of our infrastructure isn't tagged with anything; we should use a default tag set to ensure that each part of the stack is tagged with its cost code, environment, and region for use in the cost explorer.
> BAU: Update default tag set

- environments/production/common/alb.tf
HMRC-689
I have:
- Separated backend/frontend via ALB in production
- This is an architectural change that simplifies all of our API-only routes whilst protecting the admin ones
> HMRC-689: Separate frontend/backend in production

- environments/development/common/iam.tf
- environments/production/common/iam.tf
- environments/staging/common/iam.tf
https://transformuk.atlassian.net/browse/HMRC-670
I have Updated Access to S3 persistence/config for cds_guidance.json for all environments
- the chief_cds_guidance.json file is being deprecated
> HMRC-670 Deprecate CHIEF Guidance from Infrastructure

- environments/development/common/redis.tf
- environments/production/common/redis.tf
- environments/staging/common/redis.tf
- modules/acm/README.md
- modules/application-load-balancer/README.md
- modules/cloudwatch/README.md
- modules/ecr/README.md
- modules/elasticache-redis/README.md
- modules/rds/README.md
- modules/rds_cluster/README.md
- modules/secret/README.md
- modules/security-group/README.md
- modules/ses/README.md
I have:
- Remove admin redis in development
- Remove admin redis in staging
- Remove admin redis in production
- Updates docs
- Admin doesn't require redis anymore https://github.com/trade-tariff/trade-tariff-admin/pull/832
> BAU: Removes admin redis service

- environments/production/common/rds.tf
BAU
I have reduced the min ACU for Aurora.  From looking at the stats and manually playing with the settings it seems 16 ACU was way high for what we want.  This PR reduces it to 2 so in reality the DB should sit at a lower level and relying on autoscaling.
> BAU: Reduce Aurora min ACU

- environments/production/common/README.md
- environments/production/common/variables.tf
As part of https://transformuk.atlassian.net/browse/HMRC-789 I did some work into establishing normal. It turns out we were probably over-limiting a handful of users so this PR fixes that.
> Update rate limits per discovery work on 'normal' limits

- .circleci/config.yml
- environments/development/common/README.md
- environments/development/common/variables.tf
- environments/production/common/README.md
- environments/production/common/variables.tf
- environments/staging/common/README.md
- environments/staging/common/variables.tf
[HMRC-731](https://transformuk.atlassian.net/browse/HMRC-731)
I have:
- Replaced long-lived AWS credentials with OpenID Connect (OIDC) authentication in the CircleCI pipeline
- OIDC provides a more secure and scalable way to authenticate without storing long-lived credentials.
-
-
> HMRC-731:Update CircleCI pipeline to use OIDC-based role assumption

- environments/development/common/README.md
- environments/development/common/iam-policies.tf
- environments/development/common/iam-roles.tf
- environments/production/common/README.md
- environments/production/common/iam-policies.tf
- environments/production/common/iam-roles.tf
- environments/staging/common/README.md
- environments/staging/common/iam-policies.tf
- environments/staging/common/iam-roles.tf
[HMRC-814](https://transformuk.atlassian.net/browse/HMRC-814)
I have:
- Removed unused policy
- Altered existing ECS deployment policy to include ability to delete renamed policies
- We don't want lingering policies left over
- This is required to fix deployments of the DC
> HMRC-814: Removes unused policies

- environments/development/common/iam-policies.tf
- environments/production/common/iam-policies.tf
- environments/staging/common/iam-policies.tf
[HMRC-814](https://transformuk.atlassian.net/browse/HMRC-814)
I have:
- Added extra permission to deployment user
- This is required to enable deployments to change their execution/task policy names when I noticed these were poorly named
- I didn't see this before because I changed the name under the super admin role we've been using globally
> HMRC-814: Adds "iam:DeletePolicyVersion" to deployment role

- environments/development/common/iam-roles.tf
- environments/production/common/iam-roles.tf
- environments/staging/common/iam-roles.tf
[HMRC-827](https://transformuk.atlassian.net/browse/HMRC-827)
I have:
- Added permission to assume the deployment role in GHA for the dev-hub in development
- Added permission to assume the deployment role in GHA for the dev-hub in staging
- Added permission to assume the deployment role in GHA for the dev-hub in production
- This is needed to unblock deployments in this repo
> HMRC-827: Adds dev-hub to allowed webidentity repos

- .pre-commit-config.yaml
- environments/production/common/cloudwatch.tf
[HMRC-874](https://transformuk.atlassian.net/browse/HMRC-874)
I have:
- Updated the logging bucket's lifecycle policy to transition objects to S3 Deep Archive, and retain them for 3 years.
> HMRC-874: Keep S3 archived logs for 3 years in deep archive

- environments/development/common/iam-policies.tf
- environments/production/common/iam-policies.tf
- environments/staging/common/iam-policies.tf
[HMRC-879](https://transformuk.atlassian.net/browse/HMRC-879)
I have:
- Added iam:CreatePolicyVersion permission to the ECS role in development
- Added iam:CreatePolicyVersion permission to the ECS role in staging
- Added iam:CreatePolicyVersion permission to the ECS role in production
- This unblocks the deployments of new policy versions for the new dev-hub
> HMRC-879: Extends permissions for the ECS deployment role

- environments/production/common/README.md
- environments/production/common/iam.tf
- environments/production/common/secrets.tf
[HMRC-888](https://transformuk.atlassian.net/browse/HMRC-888)
I have:
- Added etf_configuration secret
- Updated ci_etf_policy to allow secret manager actions
- We need to migrate secrets from CircleCi to AWS Secret Manager as part of the migration to GitHub Actions
> Add etf_configuration secret & update ci_etf_policy accordingly

- environments/production/common/cloudfront-policy.tf
HMRC-948
Increases the TTL on our CF policy to cache for a day.  This will increase our cache hit ratios, decreasing traffic on the servers, but does depend on https://github.com/trade-tariff/trade-tariff-backend/pull/2127 being live and working
> HMRC-948 Increase CloudFront TTL

- .pre-commit-config.yaml
- environments/development/common/README.md
- environments/development/common/cloudfront-policy.tf
- environments/development/common/cloudfront.tf
- environments/production/common/README.md
- environments/production/common/cloudfront-policy.tf
- environments/production/common/cloudfront.tf
- environments/staging/common/README.md
- environments/staging/common/cloudfront-policy.tf
- environments/staging/common/cloudfront.tf
- modules/cloudfront/main.tf
[HMRC-973](https://transformuk.atlassian.net/browse/HMRC-973)
I have:
- This is needed because we're migrating away from having the caching configuration specified at the application level and clumsily applied with etags
> HMRC-973: Updates distribution policies

- environments/production/common/cloudfront-moved.tf
- environments/staging/common/cloudfront-moved.tf
- modules/cloudfront/README.md
- modules/cloudfront/main.tf
[HMRC-983](https://transformuk.atlassian.net/browse/HMRC-983)
I have:
- Changed the `count` arguments for Route53 resources to `for_each`.
- Added `moved` blocks to prevent the destruction/recreation of these records (these can be removed after this PR is merged and applied).
- After a change to the CDN aliases in #351, applying the production Terraform led to a failed deployment, in which it had already deleted the Route53 A records for the production CDN before stopping and exiting. This happened because `count` was used for these resources, and when their insertion order in the list changed (due to the removal of `beta.`), they all were due for deletion and recreation.
- This PR will prevent this from happening again, as `for_each` preserves insertion order and …
> HMRC-983: Make CloudFront module more robust

- environments/development/applications/.terraform.lock.hcl
- environments/development/base/.terraform.lock.hcl
- environments/development/common/.terraform.lock.hcl
- environments/development/common/README.md
- environments/development/common/iam-policies.tf
- environments/development/common/iam-roles.tf
- environments/production/applications/.terraform.lock.hcl
- environments/production/base/.terraform.lock.hcl
- environments/production/common/.terraform.lock.hcl
- environments/production/common/README.md
- environments/production/common/iam-policies.tf
- environments/production/common/iam-roles.tf
- environments/staging/applications/.terraform.lock.hcl
- environments/staging/base/.terraform.lock.hcl
- environments/staging/common/.terraform.lock.hcl
- environments/staging/common/README.md
- environments/staging/common/iam-policies.tf
- environments/staging/common/iam-roles.tf
[HMRC-893](https://transformuk.atlassian.net/browse/HMRC-893)
I have:
- Added the database-backups resource to the ci_lambda_deployment_policy S3 bucket
- Included the trade-tariff-lambdas-database-backups repository in the serverless_lambda_ci_role
- These updates are part of the ongoing migration to GitHub Actions and are required to ensure the correct permissions and access are in place for the new workflow.
> HMRC-893: add lambdas-database-backups permissions

- environments/development/common/README.md
- environments/development/common/secrets.tf
- environments/development/common/variables.tf
- environments/production/common/README.md
- environments/production/common/secrets.tf
- environments/production/common/variables.tf
- environments/staging/common/README.md
- environments/staging/common/secrets.tf
- environments/staging/common/variables.tf
HMRC-977
Adds configuration required for GovUK Notify
Related to https://github.com/trade-tariff/trade-tariff-backend/pull/2216
> HMRC-977-Config for GovUK Notify

- environments/development/common/iam-policies.tf
- environments/production/common/iam-policies.tf
- environments/staging/common/iam-policies.tf
[HMRC-896](https://transformuk.atlassian.net/browse/HMRC-896)
I have:
- Added more permissive EC2 permissions
- This is not quite right and given we're restricting it to EC2 in an generally unused region this should be fine
> HMRC-896: Adjusts permissions of ami builder role

- environments/development/common/iam-policies.tf
- environments/development/common/iam-roles.tf
- environments/development/common/iam.tf
- environments/production/common/iam-policies.tf
- environments/production/common/iam.tf
- environments/production/common/s3.tf
- environments/staging/common/iam-policies.tf
[HMRC-896](https://transformuk.atlassian.net/browse/HMRC-896)
I have:
- Reinstated ami perms
- Added cross account read-only access to the models bucket to the serverless role
- Added an extended session duration for the FPO models role
- Removed some extra restrictive conditions
- I've reinstated the ami role permissions as this was adjusted to debug permissions by being permissive and not a long term solution
> HMRC-896: Permissions adjustments for FPO search

- environments/production/common/alb.tf
[HMRC-1039](https://transformuk.atlassian.net/browse/HMRC-1039)
I have:
- Altered the merged dev hub target group to listen on the hub.* domain
- Removed old dev hub target groups/listener rules
- This is needed for users to get migrated to the new dev hub
> HMRC-1039: Migrate production dev hub to merged dev-hub

- environments/production/common/secrets.tf
BAU_
I have:
- Added secret to prod env
- db-replicate-configuration secret is only needed in dev and staging. But without this in prod env, deployment failed as terrafomr looking for the resource.
-
-
> BAU_: Create place holder for db-replicate-configuration to fix deployment

- environments/development/common/iam-policies.tf
- environments/production/common/.terraform.lock.hcl
- environments/production/common/README.md
- environments/production/common/iam-policies.tf
- environments/staging/common/.terraform.lock.hcl
- environments/staging/common/iam-policies.tf
I have:
Added `cognito-idp:DescribeUserPool` permission for deploy role
Identity service needs to retrieve details of cognito service during build
> Add cognito permission to deploy role

- environments/development/common/s3.tf
- environments/development/common/ses.tf
- environments/production/common/ses.tf
- environments/staging/common/s3.tf
- environments/staging/common/ses.tf
- modules/ses/main.tf
- modules/ses/variables.tf
https://transformuk.atlassian.net/browse/HMRC-938
I have:
- Added inbound emain configuration for ses service
- We have a need for an email address which we can send to for testing purposes. SES has an email receiving feature which can dump the email to an S3 bucket.
-
-
> HMRC-938: Create a receiving email address that dumps to S3

- environments/development/common/README.md
- environments/development/common/iam-roles.tf
[HMRC-1099](https://transformuk.atlassian.net/browse/HMRC-1099)
I have:
- Added missing attachment for tech-docs role in development
- This is required to unblock tech-docs deployments
> HMRC-1099: Adds missing iam-role-attachment for tech docs in development

- environments/development/common/rds.tf
- environments/staging/common/rds.tf
[HMRC-1140](https://transformuk.atlassian.net/browse/HMRC-1140)
I have:
- Altered the ACU max (previously 512 GB of memory) in development
- Altered the ACU max (previously 512 GB of memory) in staging
- This amount of total scalable capacity is insane for any of our environments
> HMRC-1140: Shrink maximum ACUs in aurora development/staging postgres

- environments/development/common/alb.tf
- environments/production/common/alb.tf
- environments/staging/common/alb.tf
I have:
- Fixed routes in development
- Added user api routes in staging and production
- To make myott service work in all environments
> Enable user api route in all environments

- environments/development/common/alb.tf
- environments/development/common/ecr.tf
- environments/development/common/iam-policies.tf
- environments/development/common/locals.tf
- environments/development/common/variables.tf
- environments/production/common/alb.tf
- environments/production/common/ecr.tf
- environments/production/common/iam-policies.tf
- environments/staging/common/alb.tf
- environments/staging/common/ecr.tf
- environments/staging/common/iam-policies.tf
- environments/staging/common/locals.tf
- environments/staging/common/variables.tf
[HMRC-694](https://transformuk.atlassian.net/browse/HMRC-694)
I have:
- Removed duty calculator route in development ALB
- Removed duty calculator route in staging ALB
- Removed duty calculator route in production ALB
- Removed unused non-secret SSM parameters for ECR repo
- We're merging the duty calculator into the frontend (see https://github.com/trade-tariff/trade-tariff-frontend/pull/2339)
> HMRC-694: Drop duty-calculator routes

- .pre-commit-config.yaml
- environments/development/common/.terraform.lock.hcl
- environments/development/common/iam-roles.tf
- environments/development/common/secrets.tf
- environments/production/applications/locals.tf
- environments/production/common/iam-roles.tf
- environments/production/common/secrets.tf
- environments/staging/applications/locals.tf
- environments/staging/common/iam-roles.tf
- environments/staging/common/secrets.tf
- modules/ecr/locals.tf
[HMRC-694](https://transformuk.atlassian.net/browse/HMRC-694)
I have:
- Tidy up duty calculator in development
- Tidy up duty-calculator in staging
- Tidy up duty calculator in production
- Remove duty calculator from ECR locals
- These are no longer required
> HMRC-694: Tidy up duty calculator infrastructure

- environments/development/common/s3.tf
- environments/production/common/s3.tf
- environments/staging/common/s3.tf
I have:
- Rotate database backups and simplify versioning in development
- Rotate database backups and simplify versioning in staging
- Rotate database backups and simplify versioning in production
- Most of our buckets absolutely do not need versioning (the one exception really is the persistence buckets but only in production)
- Backups are now being partitioned day-by-day so we have a bit of a history https://github.com/trade-tariff/trade-tariff-lambdas-database-backups/pull/6
- Reduces costs and complexity without diminishing DR
> HMRC-1165: Simplify versioning and add backup rotation

- environments/development/common/iam-roles.tf
- environments/development/common/rds.tf
- environments/staging/common/rds.tf
[HMRC-1352](https://transformuk.atlassian.net/browse/HMRC-1352)
I have:
- Added `trade-tariff-admin` repo to the `preview` app OIDC allowed repos
- Edit provider versions
- Deleted the now-unused Aurora clusters for the admin database in development and staging environments
- This is needed as part of the preview app replication in the admin repo 
- The admin app has migrated to SQLite3, making these database clusters redundant.
> HMRC-1352: Add trade-tariff-admin to preview app OIDC allowed repos

- environments/production/common/redis.tf
[HMRC-1351](https://transformuk.atlassian.net/browse/HMRC-1351)
I have:
- Beefed up `redis-frontend-production` to `cache.r4.large`.
- The current `cache.t3.medium` is being maxed out at 100%. `cache.r4.large` seems to be a pretty direct upgrade.
> HMRC-1351: Scale up production frontend Redis

- CODEOWNERS
BAU
I have:
- Added willfish to CODEOWNERS
- I figure this is sensible whilst Neil is off but really also I'm fairly familiar with this repo
> BAU: Temporarily adds willfish to CODEOWNERS

- .tool-versions
- environments/production/common/iam-policies.tf
- environments/staging/common/iam-policies.tf
[HMRC-1446](https://transformuk.atlassian.net/browse/HMRC-1446)
I have:
- Updated IAM permissions for the GitHub Actions deployment role to allow `s3:DeleteObject` on the Terraform state lockfile object in the S3 backend.
- Without this permission, Terraform cannot release the state lock, leading to errors during planning or applying.
- [Terraform `use_lockfile` docs](https://developer.hashicorp.com/terraform/language/settings/backends/s3#use_lockfile)
> HMRC-1446: Fix S3 DeleteObject permission for Terraform state lockfile

- environments/development/common/iam-roles.tf
- environments/staging/common/iam-roles.tf
I have:
- Added `trade-tariff-admin` to the list of access allowed repos in the e2e testing role in staging and dev
- We need that to enable the e2e test run for the admin app
> BAU: Add admin repo to the e2e test role

- common/lambda/trade-tariff-identity-create-auth-challenge/lambda_function.rb
- environments/development/common/cognito-identity.tf
[HMRC-1526](https://transformuk.atlassian.net/browse/HMRC-1526)
I have:
- HMRC-1526: Removes consumer from create-auth-challenge lambda
- HMRC-1527: Adds admin and portal consumer to identity cognito portal
- This is part of the configuration of passwordless authentication for both the admin and portal applications
> HMRC-1526: Removes unused consumer/cognito group

- environments/development/common/rds.tf
- environments/staging/common/rds.tf
[HMRC-1604](https://transformuk.atlassian.net/browse/HMRC-1604)
I have:
- Bumps postgresql to 17.6 in development
- Bumps postgresql to 17.6 in staging
- This is required to prove 17 in live environments before we promote to production
> HMRC-1604: Postgres 17

- environments/development/common/iam-roles.tf
- environments/staging/common/iam-roles.tf
BAU
I have:
- Added dev hub to repos that can assume e2e tests role
- This is needed to run the FPO tests there
> BAU: Adds dev hub repo to run FPO tests
