trade-tariff/trade-tariff-platform-aws-terraform

environments/development/common/README.md
environments/development/common/cloudwatch.tf
environments/development/common/locals.tf

The third PR in the series 😇 
I have:
- Added IAM policy for the KMS key
- The log group is complaining at me with AccessDenied 😢

BAU: Add key policy for cloudwatch logs

---

.pre-commit-config.yaml
environments/common/cloudwatch/.terraform.lock.hcl
environments/common/cloudwatch/README.md
environments/common/cloudwatch/cloudwatch.tf
environments/common/cloudwatch/locals.tf
environments/common/cloudwatch/outputs.tf
environments/common/cloudwatch/variables.tf
environments/common/cloudwatch/versions.tf
environments/development/common/README.md
environments/development/common/cloudwatch.tf
environments/development/common/redis.tf

I have:
- Moved all CloudWatch configuration into a module
- Called the module in `development`
- Bumped pre-commit hooks
- The configuration is getting big enough/complex enough to warrant this

BAU: Create CloudWatch Module

---

.pre-commit-config.yaml
environments/development/common/README.md
environments/development/common/opensearch.tf
tfsec.yml

I have:
- Created a new IAM user for OpenSearch use with permissions on OS and the S3 buckets.
- We'll need credentials to create packages in the cluster.

HOTT-3551: Create OpenSearch User

---

environments/common/rds/README.md
environments/common/rds/outputs.tf
environments/development/common/README.md
environments/development/common/rds.tf

I have:
- Created a new SecretsManager secret for the backend database connection string.
- The connection string that we give the backend app needs to be in a specific format.

BAU: Create Backend DB Connection String

---

environments/development/common/rds.tf

I have:
- Added the database name to the endpoint secret.
- We need this so the backend can access the db

BAU: Add DB Name to Endpoint Secret

---

environments/development/common/secrets.tf

I have:
- Altered naming of secrets to follow common pattern
- This is for consistency and was low-hanging fruit

BAU: Standardise naming of secrets

---

environments/development/common/README.md
environments/development/common/secrets.tf
environments/development/common/variables.tf

I have:
- Added secrets for the signon app.
- We'll need to consume them downstream when setting up the signon service.

BAU: Add Signon Secrets

---

.circleci/config.yml
environments/common/ecr/README.md
environments/common/ecr/ecr.tf
environments/development/common/README.md
environments/production/common/README.md
environments/production/common/ecr.tf
environments/production/common/variables.tf
environments/production/common/versions.tf

I have:
- Added - Common ECR repo in Production account
- Added - Cross-account ECR policy for development and staging account access
I am doing this because: 
- We want to have common ECR repo so that we are not duplicating the repos across multiple AWS accounts and not keeping multiple copies of images.

HOTT-3852 - Revise ECR Strategy

---

.circleci/config.yml
environments/production/terragrunt.hcl
environments/staging/terragrunt.hcl

I have:
- Added terragrunt config to staging and production environments
- Deploying infrastructure to staging and production for the first time

HOTT-3852 - Add terragrunt config to staging and production environments

---

.circleci/config.yml
environments/production/applications/terragrunt.hcl
environments/production/base/terragrunt.hcl
environments/production/common/ecr.tf
environments/staging/applications/terragrunt.hcl
environments/staging/base/terragrunt.hcl
environments/staging/common/terragrunt.hcl

I have:
- Fix for ECR repo policies
- Allowing access to Production ECR repos from staging and developement environments.

HOTT-3852 - Fix ECR repo policies 

---

environments/development/common/README.md
environments/development/common/locals.tf
environments/development/common/variables.tf
environments/production/common/ecr.tf
environments/staging/applications/README.md
environments/staging/applications/versions.tf
environments/staging/base/README.md
environments/staging/base/versions.tf
environments/staging/common/README.md
environments/staging/common/ecr.tf
environments/staging/common/locals.tf
environments/staging/common/variables.tf
environments/staging/common/versions.tf

I have:
- Altered ECR urls on Development account with Production ECR repo urls & added these urls on Staging account also.
- Making use of common ECR repo in Production account

HOTT-3852 Update Production ECR repository urls on development and staging accounts SSM param store

---

environments/production/applications/.terraform.lock.hcl
environments/production/base/.terraform.lock.hcl
environments/production/common/.terraform.lock.hcl
environments/production/common/README.md
environments/production/common/locals.tf
environments/production/common/rds.tf
environments/production/common/secrets.tf
environments/production/common/variables.tf

I have:
- Removed the MySQL database for the signon app in production.
- Removed signon secrets and their variables in production.
- The signon app is not run by us in production, it's run by GDS.

BAU: Remove redundant Signon resources

---

.pre-commit-config.yaml
environments/common/application-load-balancer/alb.tf
environments/common/ecr/ecr.tf
environments/common/elasticache-redis/elasticache-redis.tf
environments/common/rds/rds.tf
environments/common/security-group/security-group.tf
environments/development/applications/dynamodb.tf
environments/development/base/vpc.tf
environments/development/common/cloudwatch.tf
environments/development/common/opensearch.tf
environments/development/common/redis.tf
environments/development/common/s3.tf
environments/production/applications/dynamodb.tf
environments/production/base/vpc.tf
environments/production/common/cloudwatch.tf
environments/production/common/opensearch.tf
environments/production/common/s3.tf
environments/staging/applications/dynamodb.tf
environments/staging/base/vpc.tf
environments/staging/common/cloudwatch.tf
environments/staging/common/opensearch.tf
environments/staging/common/redis.tf
environments/staging/common/s3.tf

I have:
- This is currently abandonware until we're ready to migrate to a new tool

BAU: Tfsec tidies

---

environments/development/common/README.md
environments/development/common/acm.tf
environments/development/common/cloudfront.tf
environments/development/common/s3.tf

Jira link
[HOTT-2803](https://transformuk.atlassian.net/browse/HOTT-2803)
I have:
- Added API Docs infrastructure - cloudfront, s3 bucket

HOTT-2803 - Create API Docs infrastructure on development account

---

environments/development/common/README.md
environments/development/common/secrets.tf
environments/development/common/variables.tf
environments/production/common/README.md
environments/production/common/secrets.tf
environments/production/common/variables.tf
environments/staging/common/README.md
environments/staging/common/secrets.tf
environments/staging/common/variables.tf

I have:
- Added sync host secret
- This is for the CDS UK worker downloads

BAU: Adds new secret for sync host

---

environments/production/common/opensearch.tf
environments/staging/common/opensearch.tf

I have:
- Fixes broken policy document
- This was noticed when updating secrets

BAU: Fixes broken action in policy doc

---

environments/production/common/README.md
environments/production/common/cloudfront.tf
environments/production/common/s3.tf
environments/staging/common/README.md
environments/staging/common/cloudfront.tf
environments/staging/common/s3.tf

Jira link
[HOTT-2803](https://transformuk.atlassian.net/browse/HOTT-2803)
I have:
- Set api docs cloudfront origin to s3 bucket

Hott 2803 - Set api docs cloudfront origin to s3 bucket

---

environments/development/common/README.md
environments/development/common/acm.tf
environments/development/common/secrets.tf
environments/development/common/variables.tf
environments/production/common/README.md
environments/production/common/secrets.tf
environments/production/common/variables.tf
environments/staging/common/README.md
environments/staging/common/secrets.tf
environments/staging/common/variables.tf

https://transformuk.atlassian.net/browse/HOTT-3958
I have added/removed/altered:
- We're moving to data dog

HOTT-3958: Remove New Relic

---

environments/development/common/README.md
environments/development/common/rds.tf
environments/production/common/README.md
environments/production/common/rds.tf
environments/staging/common/README.md
environments/staging/common/rds.tf

I have:
- Added a Postgres instance for the Admin app
- We need a separate one for this service

BAU: Add Admin Postgres

---

environments/development/common/README.md
environments/development/common/iam.tf

I have:
- Added perms for the ci user for deploying lambda functions in dev to delete resources
- This is required for cleanup

BAU: Updates execution role perms

---

environments/common/rds/data.tf
environments/common/rds/locals.tf
environments/common/security-group/security-group.tf

[ci skip]
I have:
- Added security group rules for MySQL ports in the RDS SG.
- We need to be able to access all the databases.

BAU: Add MySQL port openings for RDS SG

---

environments/development/common/README.md
environments/development/common/secrets.tf
environments/development/common/variables.tf
environments/staging/common/README.md
environments/staging/common/secrets.tf
environments/staging/common/variables.tf

I have:
- Added key derivation salt secret for Signon

BAU: Add key derivation salt secret for Signon

---

README.md
environments/production/common/s3.tf

[HOTT-2976](https://transformuk.atlassian.net/browse/HOTT-2796)
I have:
- Added a production reports bucket.
- Minor README changes.
- We need one for migrating the `trade-tariff-reporting` bucket.
- OpenTF is now OpenTofu.

HOTT-2976: Create Reporting Bucket

---

environments/development/common/cloudwatch.tf
environments/production/common/cloudwatch.tf
environments/staging/common/cloudwatch.tf

[HOTT-4080
](https://transformuk.atlassian.net/browse/HOTT-4080)
I have:
- Added lifecycle rule to log buckets to expire old objects

HOTT-4080 - Enable logs buckets lifecycle rule to expire old objects

---

environments/common/cloudwatch/cloudwatch.tf
environments/development/common/README.md
environments/development/common/cloudwatch.tf

HOTT-4088
I have:
- Added cloudwatch logs export to s3

HOTT-4088 - added cloudwatch logs export to s3

---

environments/production/common/README.md
environments/production/common/cloudwatch.tf
environments/staging/common/README.md
environments/staging/common/cloudwatch.tf

HOTT-4088
I have:
- Added cloudwatch logs export to s3 in staging and production accounts

HOTT-4088 - added cloudwatch logs export to s3 staging and production accounts

---

.circleci/config.yml
environments/common/application-load-balancer/README.md
environments/common/application-load-balancer/outputs.tf
environments/development/common/README.md
environments/development/common/slack-notify.tf
environments/production/common/README.md
environments/production/common/slack-notify.tf

[HOTT-4081](https://transformuk.atlassian.net/browse/HOTT-4081)
I have:
- Added custom terraform image with python3 to run CirlceCI builds
- Added cloudwatch alarms and slack alerts

HOTT-4081 cloudwatch alarms and slack alerts

---

environments/production/common/slack-notify.tf

https://transformuk.atlassian.net/browse/HOTT-4081
I have:
- Updated slack channel and alarm threshold

HOTT-4081 - updated slack channel and alarm threshold

---

environments/production/common/slack-notify.tf

https://transformuk.atlassian.net/browse/HOTT-4081
I have:
- Added dns healthcheck-id for slack notification

HOTT-4081 - dns healthcheck-id update

---

environments/development/common/s3.tf
environments/production/common/s3.tf
environments/staging/common/s3.tf

I have:
- Added reporting bucket to development
- Added reporting bucket to staging
- This is needed to treat our environments like cattle not pets (e.g. no special casing in production)

HOTT-2796: Adds reporting buckets to dev/staging

---

environments/common/ses/.terraform.lock.hcl
environments/common/ses/README.md
environments/common/ses/main.tf
environments/common/ses/variables.tf
environments/common/ses/versions.tf
environments/development/common/README.md
environments/development/common/ses.tf
environments/production/common/README.md
environments/production/common/ses.tf
environments/staging/common/README.md
environments/staging/common/ses.tf

[HOTT-4310](https://transformuk.atlassian.net/browse/HOTT-4310)
I have:
- Added a small SES module in `environments/common/ses`
- Added SES in development, staging, and production
- We have this done by hand, so need to take this into Terraform

HOTT-4310: SES Verified Identity, DNS TXT Records

---

environments/development/common/README.md
environments/development/common/acm.tf
environments/development/common/cloudfront.tf
environments/development/common/s3.tf
environments/production/common/README.md
environments/production/common/cloudfront.tf
environments/production/common/s3.tf
environments/staging/common/README.md
environments/staging/common/cloudfront.tf
environments/staging/common/s3.tf

I have:
- This is required to enable OAI permissions

HOTT-4358: Bumps cloudfront module

---

environments/staging/common/cloudfront.tf

I have:
- Fixed broken reference to origin
- Its broken

HOTT-4358: Rename origin

---

environments/common/ecr/locals.tf
environments/development/common/s3.tf
environments/production/common/s3.tf
environments/staging/common/s3.tf

I have:
- Added FPO search ECR repos in each environment
- Added S3 buckets for storing machine learning models
- These are prerequisites to deploying docker images containing built machine learning models

HOTT-4388: Adds ECR and S3 buckets for deploying FPO lambdas

---

environments/common/ecr/locals.tf

I have:
- Added `database-backups` ECR repo for backup Lambda container
- Sorted applications list

BAU: Add ECR Repo for Database Backups

---

environments/development/common/README.md
environments/development/common/ecr.tf
environments/development/common/locals.tf
environments/production/applications/locals.tf
environments/staging/common/README.md
environments/staging/common/locals.tf
environments/staging/common/variables.tf

I have:
- Removed development ECR repositories.
- Added SSM parameters for all ECR repos that were missing.
- We don't need the ECR repositories anymore in development since we're using production for all the accounts.

BAU: Delete Dev ECR

---

environments/production/common/README.md
environments/production/common/variables.tf

I have:
- Added new domain
- To get the ALB working

BAU: Fixes production apply step

---

environments/development/common/iam.tf
environments/production/common/iam.tf
environments/staging/common/iam.tf

I have:
- Added more permissions for the serverless user
- These were missing

HOTT-4367: Add permissions for API gateway and ECR to lambda user

---

environments/common/security-group/security-group.tf

I have:
- Updated the ECS security group ingress/egress to be more specific about port ranges.
- It was identified as a loose set of rules in security review

HOTT-4444: Security Group Review

---

environments/staging/common/iam.tf

I have:
- Altered the zone we have access to in staging custom domains to be sandbox
- This is needed since we're using sandbox not the main domain in staging

BAU: Use sandbox for custom domain

---

environments/common/security-group/security-group.tf

I have:
- Added 8080 ingress to ECS
- I missed adding it in the prior PR

HOTT-4444: Re-add 8080 ingress

---

environments/development/common/README.md
environments/development/common/cloudfront-policy.tf
environments/development/common/cloudfront.tf
environments/production/common/.terraform.lock.hcl
environments/production/common/README.md
environments/production/common/cloudfront-policy.tf
environments/production/common/cloudfront.tf
environments/production/common/locals.tf
environments/staging/common/README.md
environments/staging/common/cloudfront-policy.tf
environments/staging/common/cloudfront.tf

[HOTT-4439](https://transformuk.atlassian.net/browse/HOTT-4439)
I have:
- Added a CloudFront response headers policy.
- We need to supply some extra headers in all our responses

HOTT-4439: Create Response Headers Policy

---

environments/common/rds/README.md
environments/common/rds/rds.tf
environments/common/rds/variables.tf
environments/production/common/rds.tf

[HOTT-4307](https://transformuk.atlassian.net/browse/HOTT-4307)
I have:
- Bump instance size in production
- Make production instance multi-AZ
- Postgres is not big enough in production

HOTT-4307: Bump RDS Instance Sizing in Production

---

environments/development/common/README.md
environments/development/common/secrets.tf
environments/development/common/variables.tf
environments/production/common/README.md
environments/production/common/secrets.tf
environments/production/common/variables.tf
environments/staging/common/README.md
environments/staging/common/secrets.tf
environments/staging/common/variables.tf

I have:
- Added sentry dsn secrets for development
- Added sentry dsn secrets for staging
- Added sentry dsn secrets for production
- These are required to enable the SQP to notify sentry

BAU: Adds sentry dsn secret

---

environments/development/common/README.md
environments/development/common/secrets.tf
environments/development/common/variables.tf
environments/production/common/README.md
environments/production/common/secrets.tf
environments/production/common/variables.tf
environments/staging/common/README.md
environments/staging/common/secrets.tf
environments/staging/common/variables.tf

I have:
- Added slack webhook url secret
- This is used by the backend

BAU: Adds slack webhook url secret

---

environments/development/common/README.md
environments/development/common/secrets.tf
environments/development/common/variables.tf
environments/production/common/README.md
environments/production/common/secrets.tf
environments/production/common/variables.tf
environments/staging/common/README.md
environments/staging/common/secrets.tf
environments/staging/common/variables.tf

I have:
- Added XE api secrets to development
- Added XE api secrets to staging
- Added XE api secrets to production
- This is required for the automated exchange rates to actually work

BAU: Adds XE api secrets

---

environments/development/common/cloudfront-policy.tf
environments/production/common/cloudfront-policy.tf
environments/staging/common/cloudfront-policy.tf

I have:
- Fixes CORs preflight request policy
- This now matches the permissive policy of the application and enables preflight requests

BAU: Fixes CORs policy to match application

---

environments/production/common/README.md
environments/production/common/iam.tf

I have:
- Added electronic-tariff-file context user
- This is required to give the user permissions to the configured bucket

BAU: Adds user for the electronic-tariff-file circle ci context

---

environments/production/common/iam.tf

I have:
- Added `ecr:GetAuthorizationToken` to releases user policy.
- We need it to login to ECR.

HOTT-4598: Add ecr:GetAuthorizationToken Action

---

environments/development/common/rds.tf
environments/production/common/rds.tf
environments/staging/common/rds.tf

I have:
- Added password to read-only user connection string.
- RDS users need a password.

BAU: Set Readonly user with Password

---

environments/development/common/README.md
environments/development/common/secrets.tf
environments/development/common/variables.tf
environments/production/common/README.md
environments/production/common/secrets.tf
environments/production/common/variables.tf
environments/staging/common/README.md
environments/staging/common/secrets.tf
environments/staging/common/variables.tf

I have:
- Added development secret for green lanes api token
- Added staging secret for green lanes api token
- Added production secret for green lanes api token
- This is required for authentication in the green lanes api

HOTT-4831: Adds development green lanes api tokens

---

environments/common/ecr/ecr.tf
environments/common/ecr/locals.tf

I have:
- Updated the ECR lifecycle policy for all repositories.
- We should hang on to production images for longer.

BAU: Refine ECR Lifecycle Policy

---

environments/development/applications/.terraform.lock.hcl
environments/development/applications/README.md
environments/development/applications/versions.tf
environments/development/common/.terraform.lock.hcl
environments/development/common/README.md
environments/development/common/cognito.tf
environments/development/common/ecr.tf
environments/production/common/ecr.tf
environments/staging/common/ecr.tf

I have:
- Added a Cognito user pool and pool client for the FPO developer hub (in Development only for now). 
- We want to play with this and get the config right before we put it in the upper environments.

FPO-134: Add Cognito (Dev)

---

environments/development/common/README.md
environments/development/common/cloudfront.tf
environments/development/common/cognito.tf

I have:
- Updated the Cognito module to v1.1.1
- Added the client secret to Secrets Manager
- Added the user pool public keys URL to SSM
- We're going to use Cognito for a machine-to-machine auth flow

FPO-134: Configure Cognito for client_credentials Flow

---

environments/development/applications/dynamodb.tf
environments/production/applications/dynamodb.tf
environments/staging/applications/dynamodb.tf

[FPO-214](https://transformuk.atlassian.net/browse/FPO-214)
I have:
- Removed FpoId from the keys in users
- a range key cannot be updated in DynamoDB
-
-

FPO-214 Remove FpoId from Users keys

---

environments/development/applications/dynamodb.tf
environments/production/applications/dynamodb.tf
environments/staging/applications/dynamodb.tf

[FPO-224](https://transformuk.atlassian.net/browse/FPO-224)
I have:
- Added new table to store organisations
- Altered fpoId to organisationId in CustomerKeyApis table
I am doing this because: we need link SCP group id to users and organizations

FPO-224 Add organisations table

---

environments/development/applications/README.md
environments/development/extra-regions/us-east-1/README.md
environments/production/applications/README.md
environments/production/common/README.md
environments/production/common/iam.tf
environments/production/common/s3.tf
environments/staging/applications/README.md
environments/staging/common/README.md
environments/staging/common/iam.tf

BAU
I have:
- Added permissions to the production fpo user for read access to the models bucket
- Added permissions to the staging fpo user for read access to the models bucket
- These are blocking deployments of new models

BAU: Fixes permissions for FPO ci user

---

environments/production/common/iam.tf
environments/staging/common/iam.tf

BAU
I have:
- Added PutObject permission for the FPO user to mark a derivation as being released in staging/production

BAU: Enable PutObject for FPO user in staging/production

---

environments/development/common/README.md
environments/development/common/secrets.tf
environments/development/common/variables.tf
environments/production/common/README.md
environments/production/common/secrets.tf
environments/production/common/variables.tf
environments/staging/common/README.md
environments/staging/common/secrets.tf
environments/staging/common/variables.tf

FPO-120
I have:
- Adds development secrets for the dev hub SCP integration
- Adds staging secrets for the dev hub SCP integration
- Adds production secrets for the dev hub SCP integration
- These are required to enable integration with the SCP single sign on API using open id

FPO-120: SCP integration secrets

---

environments/development/common/README.md
environments/development/common/secrets.tf
environments/development/common/variables.tf
environments/production/common/README.md
environments/production/common/secrets.tf
environments/production/common/variables.tf
environments/staging/common/README.md
environments/staging/common/secrets.tf
environments/staging/common/variables.tf

BAU
I have:
- Added missing secret for SCP integration

BAU: Adds missing secret value for SCP

---

environments/development/applications/README.md
environments/development/applications/dynamodb.tf
environments/production/applications/README.md
environments/production/applications/dynamodb.tf
environments/staging/applications/README.md
environments/staging/applications/dynamodb.tf

[`FPO-213`](https://transformuk.atlassian.net/browse/FPO-213)
I have:
- Added AuditLog DynamoDB table.
- We need a new table to capture audit events.

FPO-213: Add AuditLog table

---

environments/development/applications/dynamodb.tf
environments/production/applications/dynamodb.tf
environments/staging/applications/dynamodb.tf

FPO-287
I have:
- Removed ScpGroupId range column from Organisations table
- This is not longer required

FPO-287: Removes ScpGroupId range column

---

environments/development/common/README.md
environments/development/common/secrets.tf
environments/development/common/variables.tf
environments/production/common/README.md
environments/production/common/secrets.tf
environments/production/common/variables.tf
environments/staging/common/README.md
environments/staging/common/secrets.tf
environments/staging/common/variables.tf

[FPO-255](https://transformuk.atlassian.net/browse/FPO-255)
I have:
- Added a GovUK Notify api key secret
- Removed ...
- Altered ...
- this is needed to send email to Dev hub users 
-
-

FPO-255 Add GovNotify configuration

---

environments/development/common/README.md
environments/development/common/secrets.tf
environments/development/common/variables.tf
environments/production/common/README.md
environments/production/common/secrets.tf
environments/production/common/variables.tf
environments/staging/common/README.md
environments/staging/common/secrets.tf
environments/staging/common/variables.tf

[FPO-307](https://transformuk.atlassian.net/browse/FPO-307)
I have:
- Added ... new secret for cookie signing
- Removed ...
- Altered ...
- it is needed to remove the hardcoded value from the code
-
-

FPO-307 Add cookie signing secret

---

environments/development/common/README.md
environments/development/common/rds.tf
environments/development/common/variables.tf
environments/production/common/README.md
environments/production/common/rds.tf
environments/production/common/variables.tf
environments/staging/common/README.md
environments/staging/common/rds.tf
environments/staging/common/variables.tf
modules/common/rds/locals.tf
modules/common/rds/variables.tf

FPO-319
I have:
- Added db cluster for the commodi-tea application
- This is needed for the application to be able to persist classifications made by users to the database

FPO-319: Adds commodi-tea database

---

environments/development/common/README.md
environments/development/common/secrets.tf
environments/development/common/variables.tf
environments/production/common/README.md
environments/production/common/secrets.tf
environments/production/common/variables.tf
environments/staging/common/README.md
environments/staging/common/secrets.tf
environments/staging/common/variables.tf

[FPO-383](https://transformuk.atlassian.net/browse/FPO-383)
I have:
- Added a new secret for commode-tea to sign cookies
- Removed ...
- Altered ...
- session cookies are required in the app
-
-

Add Cookie signing secret for Commodi tea

---

environments/development/common/README.md
environments/production/common/README.md
environments/production/common/alb.tf

BAU
I have:
- Added a temporary listener for our target groups
- A listener is required but I don't want to switchover production yet

BAU: Adds a temporary listener for our backend target groups

---

environments/production/common/alb.tf

HMRC-689
I have:
- Separate out the backend traffic completely from the frontend

HMRC-689: Separate production frontend from production backend

---

environments/production/common/alb.tf

BAU
I have:
- Altered backend listener rules to separate out the frontend/backend traffic

BAU: Separate out the frontend/backend traffic in production

---

environments/production/common/alb.tf

I have:
- Revert separation of backend/frontend

BAU: Revert separation

---

environments/production/common/README.md
environments/production/common/rds.tf

I have:
- Created an Aurora RDS cluster in the production environment.
- Testing in staging has gone well and it is now time to put this into production.

HMRC-532: Add Aurora cluster in production

---

environments/development/common/README.md
environments/development/common/rds.tf
environments/production/common/README.md
environments/production/common/rds.tf
environments/staging/common/README.md
environments/staging/common/rds.tf
modules/rds_cluster/README.md
modules/rds_cluster/rds.tf
modules/rds_cluster/variables.tf

I have:
- Added a small Aurora cluster for the Admin tool.

BAU: Create an Admin Aurora RDS cluster

---

README.md
environments/development/root.hcl
environments/production/root.hcl
environments/staging/root.hcl
flake.nix

HMRC-795
I have:
- Simplify initialisation of providers locally

HMRC-795: Simplify initialisation of providers

---

.pre-commit-config.yaml
environments/development/common/README.md
environments/development/common/rds.tf
environments/production/common/README.md
environments/production/common/rds.tf
environments/staging/common/README.md
environments/staging/common/rds.tf
modules/rds_cluster/README.md
modules/rds_cluster/locals.tf
modules/rds_cluster/rds.tf
modules/rds_cluster/variables.tf

[HMRC-725](https://transformuk.atlassian.net/browse/HMRC-725)
I have:
- Upgraded all Postgres databases to 16.8
- Postgres 13 is going end-of-life, so it's time to upgrade.

HMRC-725: Upgrade to Postgres16

---

environments/development/common/rds.tf
environments/production/common/rds.tf
environments/staging/common/rds.tf

[HMRC-827](https://transformuk.atlassian.net/browse/HMRC-827)
I have:
- Added RDS instances for the developer hub infrastructure requirements
- This is needed for the developer hub service

HMRC-827: Adds rds instances for developer-hub

---

environments/production/common/cloudwatch.tf

HMRC-874
I have:
Updated log retention for the platform logs to three years.

HMRC-874-Resolve-logging-retention

---

environments/production/common/README.md
environments/production/common/iam.tf
environments/production/common/secrets.tf

[HMRC-887](https://transformuk.atlassian.net/browse/HMRC-887)
I have:
- Added download-cds-files-configuration
- Updated ci_cds_downloader_file_policy Resource 
- This is needed as part of the migration to GH Actions

Add new cds secret

---

environments/development/common/.terraform.lock.hcl
environments/development/common/README.md
environments/development/common/iam-policies.tf
environments/development/common/iam-roles.tf
environments/production/common/.terraform.lock.hcl
environments/production/common/README.md
environments/staging/common/.terraform.lock.hcl
environments/staging/common/README.md
flake.nix
modules/acm/README.md
modules/application-load-balancer/README.md
modules/aws-notify-slack/README.md
modules/cloudfront/README.md
modules/cloudwatch/README.md
modules/cloudwatch_log_exporter/README.md
modules/cognito/README.md
modules/ecr/README.md
modules/elasticache-redis/README.md
modules/opensearch/README.md
modules/rds/README.md
modules/rds_cluster/README.md
modules/secret/README.md
modules/security-group/README.md
modules/ses/README.md
modules/waf/README.md

[HMRC-896](https://transformuk.atlassian.net/browse/HMRC-896)
I have:
- Added role for ami building

HMRC-896: Adds a new deployment role to build amis

---

environments/development/common/secrets.tf
environments/staging/common/secrets.tf

https://transformuk.atlassian.net/browse/HMRC-798
I have:
- Added a new secret to hold config values for DB replicate 
- These values needed to run DB replicate

HMRC-798: Github workflow to replicate databases into development/stagin

---

environments/development/common/rds.tf
environments/production/common/rds.tf
environments/staging/common/rds.tf

BAU_
I have: 
- Altered postgresql aurora version number
- To sync with current version running on aws
-
-

BAU_: Sync version number in config with auto updated version in aws

---

environments/development/common/.terraform.lock.hcl
environments/development/common/README.md
environments/development/common/alb.tf
environments/development/common/cloudfront.tf
environments/development/common/iam-roles.tf
environments/development/common/locals.tf
environments/development/common/secrets.tf
modules/ecr/README.md
modules/ecr/locals.tf

[HMRC-1049](https://transformuk.atlassian.net/browse/HMRC-1049)
I have:
- Added resources to enable new Identity service to be deployed to development

Add resources for Identity service in dev

---

environments/development/common/cloudfront.tf
environments/production/common/cloudfront.tf
environments/staging/common/cloudfront.tf

Adds a better CDN configuration for https://github.com/trade-tariff/trade-tariff-frontend/pull/2291

HMRC-461 More CDN'ing

---

environments/development/common/README.md
environments/development/common/variables.tf
environments/staging/common/README.md
environments/staging/common/variables.tf

BAU
I have:
- Extended rate limit staging
- Extended rate limit production
- We're hammering these environments with e2e tests and have been rate limited

BAU: Permissive rate limit on dev/staging

---

.github/workflows/deploy-to-development.yml
.github/workflows/deploy-to-production.yml
.github/workflows/deploy-to-staging.yml
environments/development/common/README.md
environments/development/common/secrets.tf
environments/development/common/variables.tf
environments/production/common/README.md
environments/production/common/secrets.tf
environments/production/common/variables.tf
environments/staging/common/README.md
environments/staging/common/secrets.tf
environments/staging/common/variables.tf

[HMRC-1152](https://transformuk.atlassian.net/browse/HMRC-1152)
I have:
- Removed unused commodi-tea secrets
- Unused, etc

HMRC-1152: Removes unused commodi-tea secrets

---

environments/development/applications/ecs.tf
environments/development/common/alb.tf
environments/production/applications/ecs.tf
environments/staging/applications/ecs.tf
modules/cloudfront/main.tf

[HMRC-1207](https://transformuk.atlassian.net/browse/HMRC-1207)
I have:
- Added path to sidekiq web in development
- Added path to sidekiq web in staging
- Added path to sidekiq web in production

HMRC-1207: Enable sidekiq web

---

common/lambda/trade-tariff-identity-create-auth-challenge/lambda_function.rb
common/lambda/trade-tariff-identity-define-auth-challenge/lambda_function.rb
common/lambda/trade-tariff-identity-verify-auth-challenge-response/lambda_function.rb

https://transformuk.atlassian.net/browse/HMRC-1192
I have:
- Updated IDs to use live Notify account
- Removed whitespace
- Making production ready

Update for new Notify account

---

environments/production/common/rds.tf

https://transformuk.atlassian.net/browse/HMRC-1400
I have:
- Upgraded production RDS instance to Postgres 16.8
- This is proven in dev and staging; now it's time to take it to production.

HMRC-1400: Upgrade Production RDS

---

environments/production/common/rds.tf

[HMRC-1604](https://transformuk.atlassian.net/browse/HMRC-1604)
I have:
- Added production RDS clone at 16.8
- This is needed to switchover later

HMRC-1604: Add production RDS 16.8 clone

---

environments/production/common/rds.tf

I have:
- This reverts commit 4856b75ef65386649836931aef50c39e26d21cd5.
- We want a full clone to replicate into

HMRC-1604: Reinstate clone database
